force-app/main/default/classes/dlrs_pse_Timecard_HeaderTest.cls
force-app/main/default/classes/dlrs_pse_Timecard_HeaderTest.cls-meta.xml
force-app/main/default/customMetadata/dlrs__LookupRollupSummary2.Get_last_date_on_estimate.md-meta.xml
force-app/main/default/customMetadata/dlrs__LookupRollupSummary2.Total_Hours_Bill_Rate_on_Milestone.md-meta.xml
force-app/main/default/customMetadata/dlrs__LookupRollupSummary2.Total_Hours_Bill_Rate_on_Project.md-meta.xml
force-app/main/default/customMetadata/dlrs__LookupRollupSummary2.Total_assigned_hours_on_Milestone.md-meta.xml
force-app/main/default/customMetadata/dlrs__LookupRollupSummary2.Total_requested_hours_on_Milestone.md-meta.xml
force-app/main/default/customMetadata/dlrs__LookupRollupSummary2.Total_requested_hours_on_Project.md-meta.xml
force-app/main/default/triggers/dlrs_pse_Timecard_HeaderTrigger.trigger
force-app/main/default/triggers/dlrs_pse_Timecard_HeaderTrigger.trigger-meta.xml

[DevOps Center] Merge WI-000026 to Integration

---

force-app/main/default/objects/pse__Proj__c/fieldSets/pse__CreateProjectFromOppAndTempProjColumns.fieldSet-meta.xml

[DevOps Center] Merge WI-000034 to Integration

---

force-app/main/default/flows/CT_Roll_Project_Forward.flow-meta.xml

[DevOps Center] Merge WI-000045 to Integration

---

force-app/main/default/objects/Account/validationRules/V1_Restrict_Account_Name_Edit.validationRule-meta.xml
force-app/main/default/objects/Account/validationRules/V2_Restrict_Acquisition_Marker_Changes.validationRule-meta.xml
force-app/main/default/objects/Account/validationRules/V3_Address_Needed_for_Client.validationRule-meta.xml
force-app/main/default/objects/Account/validationRules/V4_Audit_Category_Required.validationRule-meta.xml
force-app/main/default/objects/Lead/validationRules/V1_Blank_Company_when_Private_Client.validationRule-meta.xml

[DevOps Center] Merge WI-000054 to Integration

---

force-app/main/default/triggers/AccountTrigger.trigger
force-app/main/default/triggers/AccountTrigger.trigger-meta.xml

[DevOps Center] Merge WI-000066 to Integration

---

force-app/main/default/lightningExperienceThemes/CooperParryTheme.lightningExperienceTheme-meta.xml

[DevOps Center] Merge WI-000072 to Integration

---

force-app/main/default/pathAssistants/Account_Type.pathAssistant-meta.xml
force-app/main/default/pathAssistants/CP_Opportunity_Path.pathAssistant-meta.xml
force-app/main/default/pathAssistants/Case_Onboarding_Path.pathAssistant-meta.xml
force-app/main/default/pathAssistants/Corporate_Opportunity_Path.pathAssistant-meta.xml
force-app/main/default/pathAssistants/Person_Account_Type.pathAssistant-meta.xml

[DevOps Center] Merge WI-000074 to Integration

---

force-app/main/default/objects/Case/businessProcesses/Onboarding Support Process.businessProcess-meta.xml
force-app/main/default/objects/Case/recordTypes/Onboarding.recordType-meta.xml
force-app/main/default/objects/Opportunity/businessProcesses/CP Opportunity Process.businessProcess-meta.xml
force-app/main/default/objects/Opportunity/businessProcesses/Corporate Opportunity Process.businessProcess-meta.xml
force-app/main/default/standardValueSets/CaseStatus.standardValueSet-meta.xml
force-app/main/default/standardValueSets/OpportunityStage.standardValueSet-meta.xml

[DevOps Center] Merge WI-000076 to Integration

---

force-app/main/default/flexipages/ProjectLightningPage1.flexipage-meta.xml

[DevOps Center] Merge WI-000087 to Integration

---

force-app/main/default/flexipages/Lead_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000096 to Integration

---

force-app/main/default/flexipages/Lead_Record_Page.flexipage-meta.xml
force-app/main/default/flows/Origination_Meeting_Screen_Flow.flow-meta.xml

[DevOps Center] Merge WI-000098 to Integration

---

force-app/main/default/flexipages/Opportunity_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000106 to Integration

---

force-app/main/default/objects/Opportunity/fields/Fee_Amount__c.field-meta.xml
force-app/main/default/objects/pse__Milestone__c/fields/CP_Complete__c.field-meta.xml
force-app/main/default/objects/pse__Milestone__c/fields/Milestone_Fee_Amount__c.field-meta.xml
force-app/main/default/reportTypes/Role_Request_Summary_by_Estimate.reportType-meta.xml

[DevOps Center] Merge WI-000109 to Integration

---

force-app/main/default/groups/CP_Law.group-meta.xml
force-app/main/default/groups/Pensions.group-meta.xml
force-app/main/default/groups/Ring_Fenced.group-meta.xml
force-app/main/default/groups/Sports_and_Media.group-meta.xml
force-app/main/default/groups/UHNWI.group-meta.xml
force-app/main/default/objects/Account/fields/Confidential_Account_Area__c.field-meta.xml
force-app/main/default/objects/Opportunity/fields/Confidential_Opportunity__c.field-meta.xml

[DevOps Center] Merge WI-000111 to Integration

---

force-app/main/default/flows/Case_Continuation_Form.flow-meta.xml
force-app/main/default/objects/Case/fields/Continuation_Form_Complete_Formula__c.field-meta.xml
force-app/main/default/objects/Case/fields/Continuation_Form_Complete__c.field-meta.xml
force-app/main/default/objects/Continuation_Form__c/fields/Completed_By__c.field-meta.xml
force-app/main/default/objects/Continuation_Form__c/fields/Completed_Date__c.field-meta.xml
force-app/main/default/objects/Opportunity/fields/Private_Corporate_Opportunity__c.field-meta.xml
force-app/main/default/tabs/Continuation_Form__c.tab-meta.xml

[DevOps Center] Merge WI-000113 to Integration

---

force-app/main/default/classes/BatchCreateSharepointFolderAccount.cls
force-app/main/default/classes/CompaniesHouseController.cls
force-app/main/default/classes/SharepointCompCont.cls
force-app/main/default/classes/SmartSearchCompCont.cls
force-app/main/default/lwc/sharepointComp/sharepointComp.js
force-app/main/default/lwc/smartSearchComp/smartSearchComp.html
force-app/main/default/lwc/smartSearchComp/smartSearchComp.js
force-app/main/default/objects/Account/fields/Sharepoint_Public_Folder_ID__c.field-meta.xml
force-app/main/default/objects/Account/fields/Sharepoint_Secure_Folder_ID__c.field-meta.xml
force-app/main/default/objects/Person_with_Significant_Control__c/fields/Account__c.field-meta.xml

[DevOps Center] Merge WI-000122 to Integration

---

force-app/main/default/flows/Lead_Update_Record_Type_Upon_Conversion.flow-meta.xml
force-app/main/default/objects/Account/fields/Connector__c.field-meta.xml
force-app/main/default/objects/Account/fields/Date_Became_Client__c.field-meta.xml
force-app/main/default/objects/Lead/fields/Beauhurst_ID__c.field-meta.xml

[DevOps Center] Merge WI-000140 to Integration

---

force-app/main/default/flows/Origination_Meeting_Screen_Flow.flow-meta.xml

[DevOps Center] Merge WI-000142 to Integration

---

force-app/main/default/LeadConvertSettings/LeadConvertSettings.LeadConvertSetting-meta.xml
force-app/main/default/flows/Account_Onboarding_is_complete.flow-meta.xml
force-app/main/default/flows/Opportunity_Create_Onboarding_Case_when_Closed_Won.flow-meta.xml
force-app/main/default/objects/Account/fields/Date_Became_Client__c.field-meta.xml
force-app/main/default/objects/Account/fields/Do_Not_Create_Case__c.field-meta.xml
force-app/main/default/objects/Account/fields/Estimated_Fees__c.field-meta.xml
force-app/main/default/objects/Account/fields/Incumbent__c.field-meta.xml
force-app/main/default/objects/Account/fields/Notes__c.field-meta.xml
force-app/main/default/objects/Account/fields/Region__c.field-meta.xml

[DevOps Center] Merge WI-000145 to Integration

---

force-app/main/default/objects/User/fields/CP_Office__c.field-meta.xml
force-app/main/default/objects/User/fields/PA__c.field-meta.xml

[DevOps Center] Merge WI-000149 to Integration

---

force-app/main/default/groups/Finance_Read_Only.group-meta.xml
force-app/main/default/permissionsetgroups/cer_Certinia_Read_Only_Accounting.permissionsetgroup-meta.xml

[DevOps Center] Merge WI-000154 to Integration

---

force-app/main/default/objects/Case/fields/Approved__c.field-meta.xml

[DevOps Center] Merge WI-000156 to Integration

---

force-app/main/default/objects/Case/fields/Form_Approved__c.field-meta.xml
force-app/main/default/objects/Case/fields/PEP_SIP_RCA_Approved_checkbox__c.field-meta.xml
force-app/main/default/objects/Case/fields/PEP_SIP_RCA_Approved_formula__c.field-meta.xml
force-app/main/default/objects/Case/fields/Partner_Approved_checkbox__c.field-meta.xml
force-app/main/default/objects/Case/fields/Partner_Approved_formula__c.field-meta.xml
force-app/main/default/objects/Case/fields/Risk_Compliance_Approved_checkbox__c.field-meta.xml
force-app/main/default/objects/Case/fields/Risk_Compliance_Approved_formula__c.field-meta.xml

[DevOps Center] Merge WI-000160 to Integration

---

force-app/main/default/flexipages/Lead_Record_Page.flexipage-meta.xml
force-app/main/default/flows/Origination_Meeting_Screen_Flow.flow-meta.xml
force-app/main/default/quickActions/Lead.Handover_Notes.quickAction-meta.xml

[DevOps Center] Merge WI-000164 to Integration

---

force-app/main/default/objects/Account/fields/CP_Client_ID__c.field-meta.xml
force-app/main/default/objects/Account/fields/Legacy_Account_ID__c.field-meta.xml

[DevOps Center] Merge WI-000177 to Integration

---

force-app/main/default/flows/Account_Inactive_Validation.flow-meta.xml
force-app/main/default/flows/Account_Risk_Team_Validation.flow-meta.xml
force-app/main/default/flows/Case_Risk_Team_Validation.flow-meta.xml
force-app/main/default/flows/Case_Update_Service_Line_to_Client_when_Closed.flow-meta.xml

[DevOps Center] Merge WI-000183 to Integration

---

force-app/main/default/flexipages/Lead_Record_Page.flexipage-meta.xml
force-app/main/default/objects/Lead/fields/Source__c.field-meta.xml

[DevOps Center] Merge WI-000186 to Integration

---

force-app/main/default/flexipages/Opportunity_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000187 to Integration

---

force-app/main/default/flows/Account_Inactive_Validation.flow-meta.xml
force-app/main/default/standardValueSets/AccountType.standardValueSet-meta.xml

[DevOps Center] Merge WI-000188 to Integration

---

force-app/main/default/flows/Opportunity_Audit_Estimate_Validation.flow-meta.xml
force-app/main/default/flows/Opportunity_Submit_to_THG_Audit_Resourcing_Approval.flow-meta.xml
force-app/main/default/groups/Resourcing_Team.group-meta.xml
force-app/main/default/quickActions/Opportunity.THG_Audit_Partner_Approval.quickAction-meta.xml

[DevOps Center] Merge WI-000189 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000191 to Integration

---

force-app/main/default/flows/Account_Opt_In_Automation.flow-meta.xml
force-app/main/default/flows/Contact_Opt_In_Automation.flow-meta.xml
force-app/main/default/flows/Source_Screen_Flow.flow-meta.xml
force-app/main/default/objects/Contact/fields/Opted_In__c.field-meta.xml
force-app/main/default/objects/Lead/fields/Opted_In__c.field-meta.xml

[DevOps Center] Merge WI-000193 to Integration

---

force-app/main/default/flows/Opportunity_THG_Tax_Validation.flow-meta.xml

[DevOps Center] Merge WI-000196 to Integration

---

force-app/main/default/layouts/Account-Account Layout.layout-meta.xml
force-app/main/default/profiles/Cooper Parry Standard Platform.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard.profile-meta.xml

[DevOps Center] Merge WI-000201 to Integration

---

force-app/main/default/classes/SmartSearchAPIUtility.cls
force-app/main/default/classes/SmartSearchCompCont.cls
force-app/main/default/groups/Secure_Public_Group.group-meta.xml
force-app/main/default/lwc/smartSearchComp/smartSearchComp.css
force-app/main/default/lwc/smartSearchComp/smartSearchComp.html
force-app/main/default/lwc/smartSearchComp/smartSearchComp.js
force-app/main/default/objects/Case/fields/Case_Referred__c.field-meta.xml
force-app/main/default/objects/Smart_Search_Setting__c/fields/high_risk_id__c.field-meta.xml
force-app/main/default/objects/Smart_Search_Setting__c/fields/smart_search_url__c.field-meta.xml
force-app/main/default/remoteSiteSettings/Companies_House_Files.remoteSite-meta.xml
force-app/main/default/remoteSiteSettings/Sharepoint_API_1.remoteSite-meta.xml
force-app/main/default/remoteSiteSettings/Sharepoint_API_2.remoteSite-meta.xml
force-app/main/default/remoteSiteSettings/Smart_Search_URL.remoteSite-meta.xml

[DevOps Center] Merge WI-000203 to Integration

---

force-app/main/default/flows/CT_Update_Company_on_Expense_Report.flow-meta.xml
force-app/main/default/flows/CT_Update_Current_Estimate.flow-meta.xml
force-app/main/default/flows/CT_Update_Current_Estimate_Assignments.flow-meta.xml

[DevOps Center] Merge WI-000205 to Integration

---

force-app/main/default/flows/Case_Custom_Error_when_Status_is_Moved.flow-meta.xml

[DevOps Center] Merge WI-000206 to Integration

---

force-app/main/default/objects/Account/fields/Source__c.field-meta.xml
force-app/main/default/objects/Lead/fields/Source__c.field-meta.xml
force-app/main/default/objects/Opportunity/fields/Source__c.field-meta.xml

[DevOps Center] Merge WI-000208 to Integration

---

force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml
force-app/main/default/objects/Account/validationRules/V5_Registered_Number_Required.validationRule-meta.xml

[DevOps Center] Merge WI-000210 to Integration

---

force-app/main/default/standardValueSets/Salutation.standardValueSet-meta.xml

[DevOps Center] Merge WI-000211 to Integration

---

force-app/main/default/flows/Case_Update_Owner_to_Risk_Team_Queue.flow-meta.xml
force-app/main/default/layouts/Case-Case Layout.layout-meta.xml

[DevOps Center] Merge WI-000217 to Integration

---

force-app/main/default/objects/Case/fields/Business_Risk_Assessment_Form_checkbox__c.field-meta.xml
force-app/main/default/objects/Case/fields/Business_Risk_Assessment_Form_formula__c.field-meta.xml
force-app/main/default/objects/Case/fields/CF_CAF__c.field-meta.xml
force-app/main/default/objects/Case/fields/CF_CAF_checkbox__c.field-meta.xml
force-app/main/default/objects/Case/fields/Individual_Ongoing_Monitoring_checkbox__c.field-meta.xml
force-app/main/default/objects/Case/fields/Individual_Ongoing_Monitoring_formula__c.field-meta.xml
force-app/main/default/objects/Case/fields/Individual_Risk_Form_checkbox__c.field-meta.xml
force-app/main/default/objects/Case/fields/Individual_Risk_Form_formula__c.field-meta.xml
force-app/main/default/objects/Case/fields/Ongoing_Monitoring_checkbox__c.field-meta.xml
force-app/main/default/objects/Case/fields/Ongoing_Monitoring_formula2__c.field-meta.xml
force-app/main/default/objects/Case/fields/PEP_SIP_RCA_Approved_formula__c.field-meta.xml
force-app/main/default/objects/Client_Acceptance_Form__c/fields/Completed_By__c.field-meta.xml
force-app/main/default/objects/Client_Acceptance_Form__c/fields/Completed_Date__c.field-meta.xml
force-app/main/default/objects/Continuation_Form__c/fields/EDD_procedures__c.field-meta.xml
force-app/main/default/objects/Continuation_Form__c/fields/Form_Type__c.field-meta.xml
force-app/main/default/objects/Continuation_Form__c/fields/NB_identityverification__c.field-meta.xml
force-app/main/default/objects/Continuation_Form__c/fields/iompick10__c.field-meta.xml
force-app/main/default/objects/Continuation_Form__c/fields/iompick12__c.field-meta.xml
force-app/main/default/objects/Continuation_Form__c/fields/iompick13__c.field-meta.xml
force-app/main/default/objects/Continuation_Form__c/fields/iompick14__c.field-meta.xml
force-app/main/default/objects/Continuation_Form__c/fields/iompick15__c.field-meta.xml
force-app/main/default/objects/Continuation_Form__c/fields/iompick2__c.field-meta.xml
force-app/main/default/objects/Continuation_Form__c/fields/iompick3__c.field-meta.xml
force-app/main/default/objects/Continuation_Form__c/fields/iompick4__c.field-meta.xml
force-app/main/default/objects/Continuation_Form__c/fields/iompick5__c.field-meta.xml
force-app/main/default/objects/Continuation_Form__c/fields/iompick6__c.field-meta.xml
force-app/main/default/objects/Continuation_Form__c/fields/iompick7__c.field-meta.xml
force-app/main/default/objects/Continuation_Form__c/fields/iompick8__c.field-meta.xml
force-app/main/default/objects/Continuation_Form__c/fields/iompick9__c.field-meta.xml
force-app/main/default/objects/Lead/fields/Source_Type__c.field-meta.xml

[DevOps Center] Merge WI-000223 to Integration

---

force-app/main/default/layouts/Case-Case Layout.layout-meta.xml
force-app/main/default/layouts/Continuation_Form__c-Continuation Form Layout.layout-meta.xml

[DevOps Center] Merge WI-000228 to Integration

---

force-app/main/default/flows/FFX_PSA_Milestone.flow-meta.xml
force-app/main/default/flows/Update_Approver_on_Billing_Event_as_Project_Manager.flow-meta.xml
force-app/main/default/objects/ffscpq__Estimate_Product__c/ffscpq__Estimate_Product__c.object-meta.xml
force-app/main/default/objects/ffscpq__Estimate_Product__c/listViews/ffscpq__All.listView-meta.xml
force-app/main/default/objects/pse__Billing_Event__c/validationRules/Approval_Required.validationRule-meta.xml
force-app/main/default/workflows/pse__Billing_Event__c.workflow-meta.xml

[DevOps Center] Merge WI-000232 to Integration

---

force-app/main/default/flows/Case_BTNC_Continuation_Form.flow-meta.xml
force-app/main/default/quickActions/Case.Ongoing_Monitoring.quickAction-meta.xml

[DevOps Center] Merge WI-000233 to Integration

---

force-app/main/default/flows/Account_Ongoing_Monitoring_Schedule.flow-meta.xml

[DevOps Center] Merge WI-000235 to Integration

---

force-app/main/default/flows/Lead_Update_Incumbent.flow-meta.xml

[DevOps Center] Merge WI-000236 to Integration

---

force-app/main/default/objects/Lead/fields/Disqualification_Reason__c.field-meta.xml

[DevOps Center] Merge WI-000237 to Integration

---

force-app/main/default/objects/Lead/fields/Client_Type__c.field-meta.xml
force-app/main/default/objects/Lead/validationRules/V2_Require_Company.validationRule-meta.xml

[DevOps Center] Merge WI-000238 to Integration

---

force-app/main/default/objects/Account/validationRules/V5_Registered_Number_Required.validationRule-meta.xml

[DevOps Center] Merge WI-000239 to Integration

---

force-app/main/default/approvalProcesses/Case.CAF_Form_Approval.approvalProcess-meta.xml
force-app/main/default/approvalProcesses/Case.Escalate_Case.approvalProcess-meta.xml
force-app/main/default/approvalProcesses/Case.PEP_SIP_RCA_Approval.approvalProcess-meta.xml
force-app/main/default/approvalProcesses/Case.Partner_Approval.approvalProcess-meta.xml
force-app/main/default/approvalProcesses/Case.Risk_Compliance_Approval.approvalProcess-meta.xml

[DevOps Center] Merge WI-000240 to Integration

---

force-app/main/default/flows/Case_Client_Acceptance_Form.flow-meta.xml

[DevOps Center] Merge WI-000244 to Integration

---

force-app/main/default/flows/Case_Individual_Client_Acceptance_Form.flow-meta.xml

[DevOps Center] Merge WI-000245 to Integration

---

force-app/main/default/flexipages/Opportunity_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000246 to Integration

---

force-app/main/default/layouts/ffscpq__Estimate__c-ffscpq__Estimate Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-CT_PSA_Delivery_Project_Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-FFX PSA PSR Project Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-FFX PSA Project Detail Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-PSA Project Detail Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-pse__Project Detail Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-pse__Project Layout.layout-meta.xml
force-app/main/default/objects/CT_Expense_VAT_Types__c/listViews/All.listView-meta.xml
force-app/main/default/objects/ffscpq__Estimate__c/fields/Total_Cost_Amount__c.field-meta.xml
force-app/main/default/objects/pse__Billing_Event__c/listViews/pse__All.listView-meta.xml
force-app/main/default/objects/pse__Proj__c/fields/Original_Estimate__c.field-meta.xml
force-app/main/default/objects/pse__Resource_Request__c/listViews/pse__All.listView-meta.xml
force-app/main/default/permissionsets/Certinia_Cooper_Parry_Custom_PS.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_PSA_Permission_Set.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_User_Fields.permissionset-meta.xml
force-app/main/default/reportTypes/CT_Opportunities_with_Estimates_and_Line_Sets.reportType-meta.xml
force-app/main/default/reportTypes/Estimates.reportType-meta.xml
force-app/main/default/reportTypes/Role_Request_Summary_by_Estimate.reportType-meta.xml

[DevOps Center] Merge WI-000250 to Integration

---

force-app/main/default/layouts/pse__Proj__c-FFX PSA Project Detail Layout.layout-meta.xml
force-app/main/default/objects/pse__Proj__c/fields/Budget_Recovery_Rate__c.field-meta.xml

[DevOps Center] Merge WI-000251 to Integration

---

force-app/main/default/flows/CT_Update_Current_Estimate.flow-meta.xml
force-app/main/default/flows/FFX_PSA_Project.flow-meta.xml

[DevOps Center] Merge WI-000252 to Integration

---

force-app/main/default/flows/CT_Update_Current_Estimate.flow-meta.xml

[DevOps Center] Merge WI-000253 to Integration

---

force-app/main/default/flows/Origination_Meeting_Screen_Flow.flow-meta.xml
force-app/main/default/quickActions/Account.BD_Meeting.quickAction-meta.xml
force-app/main/default/quickActions/Account.Handover_Notes.quickAction-meta.xml

[DevOps Center] Merge WI-000262 to Integration

---

force-app/main/default/flexipages/Contact_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000263 to Integration

---

force-app/main/default/permissionsets/Cooper_Parry_PSA_Permission_Set_for_Project_Managers.permissionset-meta.xml
force-app/main/default/profiles/Cooper Parry Standard Platform.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard.profile-meta.xml

[DevOps Center] Merge WI-000265 to Integration

---

force-app/main/default/flows/Account_Update_Auditor.flow-meta.xml

[DevOps Center] Merge WI-000273 to Integration

---

force-app/main/default/classes/BatchCreateSharepointFolderCase.cls
force-app/main/default/classes/BatchCreateSharepointFolderCase.cls-meta.xml
force-app/main/default/classes/CaseTriggerHandler.cls
force-app/main/default/classes/CaseTriggerHandler.cls-meta.xml
force-app/main/default/classes/SharepointCompCont.cls
force-app/main/default/classes/SmartSearchCompCont.cls
force-app/main/default/lwc/smartSearchComp/smartSearchComp.js
force-app/main/default/objects/Case/fields/Sharepoint_Folder_ID__c.field-meta.xml
force-app/main/default/objects/Case/fields/Sharepoint_Public_Folder_ID__c.field-meta.xml
force-app/main/default/objects/Case/fields/Sharepoint_Secure_Folder_ID__c.field-meta.xml
force-app/main/default/triggers/CaseTrigger.trigger
force-app/main/default/triggers/CaseTrigger.trigger-meta.xml

[DevOps Center] Merge WI-000275 to Integration

---

force-app/main/default/flows/Recovery_rate_less_than_70_Notify_PM.flow-meta.xml
force-app/main/default/notificationtypes/Notify_PM_if_recovery_is_less_than_70.notiftype-meta.xml

[DevOps Center] Merge WI-000276 to Integration

---

force-app/main/default/classes/SmartSearchCompCont.cls

[DevOps Center] Merge WI-000280 to Integration

---

force-app/main/default/flexipages/Contact_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000282 to Integration

---

force-app/main/default/flows/Case_Update_Service_Line_to_Client_when_Closed.flow-meta.xml

[DevOps Center] Merge WI-000283 to Integration

---

force-app/main/default/flows/Source_Screen_Flow.flow-meta.xml
force-app/main/default/objects/Account/validationRules/V5_Registered_Number_Required.validationRule-meta.xml
force-app/main/default/objects/Lead/validationRules/V2_Require_Company.validationRule-meta.xml
force-app/main/default/objects/Opportunity/fields/Source__c.field-meta.xml

[DevOps Center] Merge WI-000284 to Integration

---

force-app/main/default/flexipages/Corporate_Opp_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/Opportunity_Record_Page.flexipage-meta.xml
force-app/main/default/flows/Opportunity_Update_Naming_Convention.flow-meta.xml
force-app/main/default/groups/Corporate_Finance_Group.group-meta.xml
force-app/main/default/objects/Opportunity/businessProcesses/Corporate Opportunity Process.businessProcess-meta.xml
force-app/main/default/objects/Opportunity/fields/Corporate_Finance_Notes__c.field-meta.xml
force-app/main/default/objects/Opportunity/fields/Meeting_Subtype__c.field-meta.xml
force-app/main/default/objects/Opportunity/fields/Short_Term_Opportunity__c.field-meta.xml
force-app/main/default/objects/Opportunity/validationRules/V1_Acquirer_Required_for_Completed_Deal.validationRule-meta.xml
force-app/main/default/standardValueSets/OpportunityStage.standardValueSet-meta.xml

[DevOps Center] Merge WI-000285 to Integration

---

force-app/main/default/flows/Case_Auto_Submit_Risk_Approval_after_Partner_Approval.flow-meta.xml
force-app/main/default/flows/Case_Update_Account_when_Case_is_Closed.flow-meta.xml
force-app/main/default/flows/Opportunity_Create_Onboarding_Case_when_Closed_Won.flow-meta.xml
force-app/main/default/objects/Case/fields/Confidential_Opportunity__c.field-meta.xml
force-app/main/default/objects/Client_Acceptance_Form__c/Client_Acceptance_Form__c.object-meta.xml
force-app/main/default/objects/Client_Acceptance_Form__c/fields/Completed_By__c.field-meta.xml
force-app/main/default/objects/Client_Acceptance_Form__c/fields/Completed_Date__c.field-meta.xml
force-app/main/default/objects/Client_Acceptance_Form__c/fields/Type__c.field-meta.xml
force-app/main/default/objects/Continuation_Form__c/Continuation_Form__c.object-meta.xml

[DevOps Center] Merge WI-000286 to Integration

---

force-app/main/default/objects/Case/fields/Confidential_Opportunity__c.field-meta.xml

[DevOps Center] Merge WI-000288 to Integration

---

force-app/main/default/flows/Case_Custom_Error_when_Status_is_Moved.flow-meta.xml
force-app/main/default/objects/Case/validationRules/Law_Initial_Review_User_Validation.validationRule-meta.xml

[DevOps Center] Merge WI-000290 to Integration

---

force-app/main/default/flows/Case_Continuation_Form.flow-meta.xml
force-app/main/default/flows/Case_Custom_Error_when_Status_is_Moved.flow-meta.xml
force-app/main/default/flows/Case_Update_Service_Line_to_Client_when_Closed.flow-meta.xml
force-app/main/default/objects/Case/fields/Case_Area__c.field-meta.xml
force-app/main/default/objects/Case/fields/Case_Assignment_Type__c.field-meta.xml
force-app/main/default/objects/Case/fields/Case_Type_Area__c.field-meta.xml

[DevOps Center] Merge WI-000291 to Integration

---

force-app/main/default/globalValueSets/Acquisition_Marker.globalValueSet-meta.xml
force-app/main/default/globalValueSets/Assignment_Type.globalValueSet-meta.xml
force-app/main/default/globalValueSets/Audit_Categories.globalValueSet-meta.xml
force-app/main/default/globalValueSets/Meeting_Status.globalValueSet-meta.xml
force-app/main/default/globalValueSets/Network.globalValueSet-meta.xml
force-app/main/default/globalValueSets/Primary_Sector.globalValueSet-meta.xml
force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
force-app/main/default/globalValueSets/Secondary_Sector.globalValueSet-meta.xml
force-app/main/default/globalValueSets/Service_Lines.globalValueSet-meta.xml
force-app/main/default/objects/Account/fields/Ownership.field-meta.xml
force-app/main/default/objects/Associations__c/fields/Service_Line__c.field-meta.xml
force-app/main/default/objects/Corporate_Finance_Opportunity__c/fields/Assignment_Type__c.field-meta.xml

[DevOps Center] Merge WI-000297 to Integration

---

force-app/main/default/objects/Case/recordTypes/Adhoc_Check.recordType-meta.xml
force-app/main/default/objects/Case/recordTypes/Onboarding.recordType-meta.xml
force-app/main/default/objects/Case/recordTypes/Yearly_Check.recordType-meta.xml
force-app/main/default/objects/Lead/fields/Disqualification_Reason__c.field-meta.xml

[DevOps Center] Merge WI-000300 to Integration

---

force-app/main/default/layouts/Case-Case Layout.layout-meta.xml
force-app/main/default/layouts/Contact-Contact Layout.layout-meta.xml
force-app/main/default/layouts/Lead-Lead Layout.layout-meta.xml
force-app/main/default/layouts/Opportunity-Opportunity Layout.layout-meta.xml
force-app/main/default/layouts/PersonAccount-Person Account Layout.layout-meta.xml

[DevOps Center] Merge WI-000301 to Integration

---

force-app/main/default/objects/Account/Account.object-meta.xml
force-app/main/default/objects/Account/compactLayouts/c2g__AccountCompactLayout.compactLayout-meta.xml
force-app/main/default/objects/Account/fieldSets/c2g__SelectAccountLookupColumns.fieldSet-meta.xml
force-app/main/default/objects/Account/listViews/Beauhurst_List.listView-meta.xml
force-app/main/default/objects/Account/listViews/ffaws__Customer_Accounts.listView-meta.xml
force-app/main/default/objects/Account/listViews/ffaws__OnHoldForCollections.listView-meta.xml
force-app/main/default/objects/Account/listViews/ffaws__Vendor_Accounts.listView-meta.xml
force-app/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml
force-app/main/default/objects/Account/recordTypes/cer_Customer.recordType-meta.xml
force-app/main/default/objects/Account/validationRules/FFX_Lock_Account_Currency.validationRule-meta.xml
force-app/main/default/objects/Account/webLinks/APXTConga4__Conga_Composer_OAuth.webLink-meta.xml
force-app/main/default/objects/Account/webLinks/APXTConga4__Conga_Mail_Merge.webLink-meta.xml
force-app/main/default/objects/Account/webLinks/c2g__CODAValidateBillingAddress.webLink-meta.xml
force-app/main/default/objects/Account/webLinks/c2g__CODAValidateCustomer.webLink-meta.xml
force-app/main/default/objects/Account/webLinks/c2g__CODAValidateShippingAddress.webLink-meta.xml
force-app/main/default/objects/Account/webLinks/c2g__CODAValidateVendor.webLink-meta.xml
force-app/main/default/objects/Account/webLinks/c2g__CashMatching.webLink-meta.xml
force-app/main/default/objects/Account/webLinks/fferpcore__ValidateBillingAddress.webLink-meta.xml
force-app/main/default/objects/Account/webLinks/fferpcore__ValidateShippingAddress.webLink-meta.xml
force-app/main/default/objects/Account/webLinks/pse__Account_Billing.webLink-meta.xml
force-app/main/default/objects/Account/webLinks/pse__Create_Change_Request.webLink-meta.xml

[DevOps Center] Merge WI-000303 to Integration

---

force-app/main/default/objects/Account/fields/Acquisition_Marker__c.field-meta.xml
force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
force-app/main/default/objects/Case/fields/Origin.field-meta.xml
force-app/main/default/objects/Lead/fields/Ownership__c.field-meta.xml
force-app/main/default/objects/Opportunity/fields/Win_Probability__c.field-meta.xml
force-app/main/default/objects/Referral__c/fields/Referral_Contact__c.field-meta.xml
force-app/main/default/objects/Referral__c/fields/Referral_Type__c.field-meta.xml
force-app/main/default/objects/pse__Billing_Event__c/fields/CT_Approval_Status_Project_Partner__c.field-meta.xml
force-app/main/default/queues/Origination_Queue.queue-meta.xml

[DevOps Center] Merge WI-000304 to Integration

---

force-app/main/default/objects/Account/fields/Previously_Onboarded__c.field-meta.xml
force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
force-app/main/default/objects/Case/fields/Previously_Onboarded__c.field-meta.xml
force-app/main/default/objects/Org_Wide_Settings__c/Org_Wide_Settings__c.object-meta.xml
force-app/main/default/objects/Org_Wide_Settings__c/fields/Disable_Flows__c.field-meta.xml
force-app/main/default/objects/Org_Wide_Settings__c/fields/Disable_Validation_Rules__c.field-meta.xml

[DevOps Center] Merge WI-000305 to Integration

---

force-app/main/default/email/CPTemplates.emailFolder-meta.xml

[DevOps Center] Merge WI-000306 to Integration

---

force-app/main/default/flows/Case_Custom_Error_when_Status_is_Moved.flow-meta.xml
force-app/main/default/flows/Case_Update_Owner_to_Risk_Team_Queue.flow-meta.xml
force-app/main/default/flows/Case_Update_Service_Line_to_Client_when_Closed.flow-meta.xml
force-app/main/default/flows/Survey_NPS_Score_6_or_Less.flow-meta.xml

[DevOps Center] Merge WI-000298 to Integration

---

force-app/main/default/objects/Org_Wide_Settings__c/Org_Wide_Settings__c.object-meta.xml
force-app/main/default/standardValueSets/CaseOrigin.standardValueSet-meta.xml
force-app/main/default/workflows/Case.workflow-meta.xml
force-app/main/default/workflows/Opportunity.workflow-meta.xml

[DevOps Center] Merge WI-000307 to Integration

---

force-app/main/default/customPermissions/Client_Account_Edit.customPermission-meta.xml
force-app/main/default/objects/Account/fields/Audit_Client__c.field-meta.xml
force-app/main/default/objects/Account/fields/BH_Collection_Name__c.field-meta.xml
force-app/main/default/objects/Opportunity/businessProcesses/CP Opportunity Process.businessProcess-meta.xml
force-app/main/default/objects/Opportunity/businessProcesses/Corporate Opportunity Process.businessProcess-meta.xml
force-app/main/default/objects/Opportunity/fields/Referral__c.field-meta.xml
force-app/main/default/objects/Referral__c/fields/Lead_Area__c.field-meta.xml
force-app/main/default/objects/Referral__c/fields/Opportunity__c.field-meta.xml
force-app/main/default/objects/Referral__c/fields/Referral_User__c.field-meta.xml
force-app/main/default/objects/Referral__c/fields/Referred_Contact__c.field-meta.xml
force-app/main/default/standardValueSets/OpportunityStage.standardValueSet-meta.xml
force-app/main/default/workflows/Case.workflow-meta.xml

[DevOps Center] Merge WI-000308 to Integration

---

force-app/main/default/objects/Opportunity/fields/StageName.field-meta.xml

[DevOps Center] Merge WI-000309 to Integration

---

force-app/main/default/email/unfiled$public/Opportunity_Closed_Won_Notification.email
force-app/main/default/email/unfiled$public/Opportunity_Closed_Won_Notification.email-meta.xml
force-app/main/default/email/unfiled$public/PEP_Notification_for_Case.email
force-app/main/default/email/unfiled$public/PEP_Notification_for_Case.email-meta.xml
force-app/main/default/globalValueSets/Ownership.globalValueSet-meta.xml
force-app/main/default/objects/Lead/fields/Disqualification_Reason__c.field-meta.xml
force-app/main/default/objects/Lead/fields/Status.field-meta.xml
force-app/main/default/standardValueSets/OpportunityStage.standardValueSet-meta.xml
force-app/main/default/workflows/Case.workflow-meta.xml
force-app/main/default/workflows/Opportunity.workflow-meta.xml

[DevOps Center] Merge WI-000310 to Integration

---

force-app/main/default/LeadConvertSettings/LeadConvertSettings.LeadConvertSetting-meta.xml
force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000311 to Integration

---

force-app/main/default/workflows/Case.workflow-meta.xml
force-app/main/default/workflows/Opportunity.workflow-meta.xml

[DevOps Center] Merge WI-000316 to Integration

---

force-app/main/default/objects/Case/webLinks/SendWithDocuSign.webLink-meta.xml

[DevOps Center] Merge WI-000319 to Integration

---

force-app/main/default/objects/Opportunity/businessProcesses/CP Opportunity Process.businessProcess-meta.xml
force-app/main/default/objects/Opportunity/businessProcesses/Corporate Opportunity Process.businessProcess-meta.xml

[DevOps Center] Merge WI-000320 to Integration

---

force-app/main/default/layouts/Case-Case Layout.layout-meta.xml

[DevOps Center] Merge WI-000321 to Integration

---

force-app/main/default/workflows/Opportunity.workflow-meta.xml

[DevOps Center] Merge WI-000323 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000324 to Integration

---

force-app/main/default/groups/Audit_Notification.group-meta.xml
force-app/main/default/groups/BSO_Notification.group-meta.xml
force-app/main/default/groups/Deals_Notification.group-meta.xml
force-app/main/default/groups/Law_Notification.group-meta.xml
force-app/main/default/groups/Tax_Notification.group-meta.xml

[DevOps Center] Merge WI-000326 to Integration

---

force-app/main/default/flows/CS_Gifts_Screen_Flow.flow-meta.xml
force-app/main/default/flows/Competitor_Incumbent_Flow.flow-meta.xml
force-app/main/default/flows/Corporate_Opportunity_Add_Private_Equity.flow-meta.xml
force-app/main/default/flows/Referral_Screen_Flow.flow-meta.xml

[DevOps Center] Merge WI-000327 to Integration

---

force-app/main/default/layouts/Case-Case Layout.layout-meta.xml
force-app/main/default/objects/Referral__c/fields/Opportunity_is_Corporate__c.field-meta.xml

[DevOps Center] Merge WI-000328 to Integration

---

force-app/main/default/flowDefinitions/Survey_NPS_Score_6_or_Less.flowDefinition-meta.xml
force-app/main/default/flowDefinitions/firm_wide_survey.flowDefinition-meta.xml

[DevOps Center] Merge WI-000332 to Integration

---

force-app/main/default/flows/Account_Onboarding_is_complete.flow-meta.xml
force-app/main/default/flows/Campaign_Add_Survey_Sent_Status.flow-meta.xml
force-app/main/default/objects/Account/fields/Date_Became_Client__c.field-meta.xml
force-app/main/default/pathAssistants/Default.pathAssistant-meta.xml

[DevOps Center] Merge WI-000333 to Integration

---

force-app/main/default/classes/BeauhurstAPIUtility.cls
force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml
force-app/main/default/flows/Survey_NPS_Score_6_or_Less.flow-meta.xml

[DevOps Center] Merge WI-000338 to Integration

---

force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml
force-app/main/default/flows/Campaign_Add_Survey_Sent_Status.flow-meta.xml

[DevOps Center] Merge WI-000341 to Integration

---

force-app/main/default/classes/AccountTriggerHandler.cls
force-app/main/default/classes/BeauhurstAPIUtility.cls
force-app/main/default/classes/CreateAccountsFromBHBatch.cls
force-app/main/default/classes/CreateAccountsFromBHBatch.cls-meta.xml
force-app/main/default/classes/GetCompanyIdBatch.cls

[DevOps Center] Merge WI-000339 to Integration

---

force-app/main/default/brandingSets/LEXTHEMINGCooperParryTheme.brandingSet-meta.xml

[DevOps Center] Merge WI-000345 to Integration

---

force-app/main/default/flexipages/Lead_Record_Page.flexipage-meta.xml
force-app/main/default/objects/Account/fields/Secondary_Sector__c.field-meta.xml
force-app/main/default/objects/Lead/fields/Job_Title__c.field-meta.xml
force-app/main/default/objects/Lead/fields/Secondary_Sector__c.field-meta.xml

[DevOps Center] Merge WI-000343 to Integration

---

force-app/main/default/dashboards/FFX_AcceleratePSADashboards/FFX_PSA_Operations_Dashboard.dashboard-meta.xml
force-app/main/default/dashboards/FFX_AcceleratePSADashboards/FFX_PSA_Resource_Management_Dashboard.dashboard-meta.xml
force-app/main/default/dashboards/FFX_AcceleratePSADashboards/FFX_PSA_Services_Delivery_Dashboard.dashboard-meta.xml
force-app/main/default/reports/CertiniaEstimateReports.reportFolder-meta.xml
force-app/main/default/reports/CooperParryReports.reportFolder-meta.xml

[DevOps Center] Merge WI-000347 to Integration

---

force-app/main/default/quickActions/Lead.VC_Backed.quickAction-meta.xml

[DevOps Center] Merge WI-000350 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000352 to Integration

---

force-app/main/default/applications/CP_PSA.app-meta.xml
force-app/main/default/applications/CP_PSAAdmin.app-meta.xml
force-app/main/default/applications/CP_PSA_Finance.app-meta.xml
force-app/main/default/applications/FFX_Accounts_Payable.app-meta.xml
force-app/main/default/applications/FFX_FFA_Organization_Setup.app-meta.xml
force-app/main/default/applications/c2g__Accounting_Lightning.app-meta.xml
force-app/main/default/applications/psaws__Project_Management.app-meta.xml
force-app/main/default/applications/pse__PSA_Mobile.app-meta.xml
force-app/main/default/applications/pse__PS_Enterprise_Admin_Lightning.app-meta.xml
force-app/main/default/applications/pse__PS_Enterprise_Field_Lightning.app-meta.xml
force-app/main/default/applications/pse__PS_Enterprise_Lightning.app-meta.xml
force-app/main/default/applications/pse__PS_Enterprise_Management_Lightning.app-meta.xml
force-app/main/default/applications/pse__PS_Enterprise_Operations_Lightning.app-meta.xml
force-app/main/default/objects/Contact/recordTypes/CRM_Contact.recordType-meta.xml
force-app/main/default/objects/Contact/recordTypes/PSA_Resource.recordType-meta.xml

[DevOps Center] Merge WI-000354 to Integration

---

force-app/main/default/layouts/Contact-Contact Layout.layout-meta.xml

[DevOps Center] Merge WI-000355 to Integration

---

force-app/main/default/layouts/c2g__codaBankAccount__c-c2g__Bank Layout.layout-meta.xml

[DevOps Center] Merge WI-000360 to Integration

---

force-app/main/default/lwc/companyHouseButton/companyHouseButton.js

[DevOps Center] Merge WI-000363 to Integration

---

force-app/main/default/reportTypes/Time_Variance.reportType-meta.xml
force-app/main/default/reports/CooperParryReports/Time_Variance_Report_h3d.report-meta.xml

[DevOps Center] Merge WI-000364 to Integration

---

force-app/main/default/permissionsets/Cooper_Parry_PSA_Permission_Set.permissionset-meta.xml

[DevOps Center] Merge WI-000370 to Integration

---

force-app/main/default/flexipages/Case_Record_Page.flexipage-meta.xml
force-app/main/default/layouts/Case-Case Layout.layout-meta.xml

[DevOps Center] Merge WI-000362 to Integration

---

force-app/main/default/objects/Uploader_Mapping__mdt/fields/Column_Name__c.field-meta.xml
force-app/main/default/objects/Uploader_Mapping__mdt/fields/Field_API_Name__c.field-meta.xml

[DevOps Center] Merge WI-000371 to Integration

---

force-app/main/default/groups/BD.group-meta.xml

[DevOps Center] Merge WI-000369 to Integration

---

force-app/main/default/flexipages/Case_Record_Page.flexipage-meta.xml
force-app/main/default/layouts/Case-Case Layout.layout-meta.xml

[DevOps Center] Merge WI-000376 to Integration

---

force-app/main/default/permissionsetgroups/Certinia_Revenue_Management.permissionsetgroup-meta.xml

[DevOps Center] Merge WI-000378 to Integration

---

force-app/main/default/flexipages/Lead_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000387 to Integration

---

force-app/main/default/flows/Lead_Update_Account_Lookup.flow-meta.xml

[DevOps Center] Merge WI-000388 to Integration

---

force-app/main/default/flexipages/Lead_Record_Page.flexipage-meta.xml
force-app/main/default/flows/Lead_Update_Account_Lookup.flow-meta.xml

[DevOps Center] Merge Integration to UAT

---

force-app/main/default/flows/Lead_Update_Account_Lookup.flow-meta.xml

[DevOps Center] Merge WI-000389 to Integration

---

force-app/main/default/flows/Lead_Update_Account_Lookup.flow-meta.xml

[DevOps Center] Merge WI-000390 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000391 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
force-app/main/default/standardValueSets/SalesTeamRole.standardValueSet-meta.xml

[DevOps Center] Merge WI-000392 to Integration

---

force-app/main/default/flexipages/Contact_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/Contact_Record_Page_Three_Column.flexipage-meta.xml
force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml
force-app/main/default/globalValueSets/Job_Title.globalValueSet-meta.xml
force-app/main/default/layouts/Contact-Contact Layout.layout-meta.xml
force-app/main/default/layouts/PersonAccount-Person Account Layout.layout-meta.xml
force-app/main/default/objects/Contact/fields/Job_Title__c.field-meta.xml
force-app/main/default/objects/Contact/recordTypes/CRM_Contact.recordType-meta.xml
force-app/main/default/objects/Contact/recordTypes/PSA_Resource.recordType-meta.xml

[DevOps Center] Merge WI-000393 to Integration

---

force-app/main/default/flexipages/Contact_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000394 to Integration

---

force-app/main/default/applications/standard__LightningSales.app-meta.xml
force-app/main/default/applications/standard__LightningSalesConsole.app-meta.xml

[DevOps Center] Merge WI-000395 to Integration

---

force-app/main/default/flexipages/Opportunity_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000397 to Integration

---

force-app/main/default/flexipages/Estimate_Record_Page12.flexipage-meta.xml
force-app/main/default/flexipages/Opportunity_Record_Page_Three_Column.flexipage-meta.xml

[DevOps Center] Merge WI-000398 to Integration

---

force-app/main/default/objects/Beneficial_Owner__c/fields/Title__c.field-meta.xml

[DevOps Center] Merge WI-000405 to Integration

---

force-app/main/default/flexipages/Corporate_Opp_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/Opportunity_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000406 to Integration

---

force-app/main/default/flows/Opportunity_Update_Naming_Convention.flow-meta.xml

[DevOps Center] Merge WI-000407 to Integration

---

force-app/main/default/classes/AccountTriggerHandler.cls
force-app/main/default/triggers/AccountTrigger.trigger

[DevOps Center] Merge WI-000411 to Integration

---

force-app/main/default/queues/Lifecycle_Managers.queue-meta.xml
force-app/main/default/queues/Lifecycle_Onboarding_Queue.queue-meta.xml
force-app/main/default/queues/Risk_Team_Queue.queue-meta.xml
force-app/main/default/queues/Service_Case.queue-meta.xml

[DevOps Center] Merge WI-000416 to Integration

---

force-app/main/default/flows/Opportunity_TS_TT_Estimates_Validation.flow-meta.xml

[DevOps Center] Merge WI-000420 to Integration

---

force-app/main/default/flexipages/Opportunity_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000421 to Integration

---

force-app/main/default/classes/CompanyLeadsComponentController.cls
force-app/main/default/classes/CompanyLeadsComponentController.cls-meta.xml
force-app/main/default/classes/LeadMatchingRuleUtility.cls
force-app/main/default/classes/LeadMatchingRuleUtility.cls-meta.xml
force-app/main/default/objects/Matching_Lead_Criteria__mdt/Matching_Lead_Criteria__mdt.object-meta.xml
force-app/main/default/objects/Matching_Lead_Criteria__mdt/fields/API_Name__c.field-meta.xml
force-app/main/default/objects/Matching_Lead_Criteria__mdt/fields/Is_Email__c.field-meta.xml
force-app/main/default/objects/Matching_Lead_Criteria__mdt/fields/Operator__c.field-meta.xml
force-app/main/default/objects/Matching_Lead_Criteria__mdt/fields/Order_No__c.field-meta.xml

[DevOps Center] Merge WI-000424 to Integration

---

force-app/main/default/layouts/c2g__codaCreditNote__c-FFX Sales Credit Note Layout.layout-meta.xml
force-app/main/default/profiles/Admin.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard Platform.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard.profile-meta.xml

[DevOps Center] Merge WI-000430 to Integration

---

force-app/main/default/permissionsetgroups/Cooper_Parry_PSA_Accounting.permissionsetgroup-meta.xml

[DevOps Center] Merge WI-000435 to Integration

---

force-app/main/default/profiles/Cooper Parry Standard Platform.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard.profile-meta.xml

[DevOps Center] Merge WI-000436 to Integration

---

force-app/main/default/objects/Lead/validationRules/V2_Require_Company.validationRule-meta.xml

[DevOps Center] Merge WI-000437 to Integration

---

force-app/main/default/profiles/Cooper Parry Standard Platform.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard.profile-meta.xml

[DevOps Center] Merge WI-000438 to Integration

---

force-app/main/default/flows/Case_Individual_Client_Acceptance_Form.flow-meta.xml
force-app/main/default/objects/Case/fields/Business_Risk_Assessment_Form_formula__c.field-meta.xml
force-app/main/default/objects/Case/fields/Individual_Risk_Form_formula__c.field-meta.xml

[DevOps Center] Merge WI-000439 to Integration

---

force-app/main/default/flexipages/ProjectLightningPage1.flexipage-meta.xml

[DevOps Center] Merge WI-000440 to Integration

---

force-app/main/default/flows/Case_Client_Acceptance_Form.flow-meta.xml
force-app/main/default/flows/Case_Individual_Client_Acceptance_Form.flow-meta.xml

[DevOps Center] Merge WI-000441 to Integration

---

force-app/main/default/permissionsets/Cooper_Parry_User_Fields.permissionset-meta.xml

[DevOps Center] Merge WI-000442 to Integration

---

force-app/main/default/profiles/Cooper Parry Standard Platform.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard.profile-meta.xml

[DevOps Center] Merge WI-000446 to Integration

---

force-app/main/default/flexipages/Case_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000445 to Integration

---

force-app/main/default/profiles/Cooper Parry Standard Platform.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard.profile-meta.xml

[DevOps Center] Merge WI-000447 to Integration

---

force-app/main/default/profiles/Cooper Parry Standard Platform.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard.profile-meta.xml

[DevOps Center] Merge WI-000448 to Integration

---

force-app/main/default/flows/Case_Client_Acceptance_Form.flow-meta.xml

[DevOps Center] Merge WI-000451 to Integration

---

force-app/main/default/flows/Case_Client_Acceptance_Form.flow-meta.xml

[DevOps Center] Merge WI-000452 to Integration

---

force-app/main/default/profiles/Cooper Parry Standard Platform.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard.profile-meta.xml

[DevOps Center] Merge WI-000453 to Integration

---

force-app/main/default/layouts/Event-Event Layout.layout-meta.xml
force-app/main/default/objects/Activity/fields/Meeting_Subtype__c.field-meta.xml
force-app/main/default/quickActions/NewEvent.quickAction-meta.xml

[DevOps Center] Merge WI-000455 to Integration

---

force-app/main/default/flows/CT_Calculate_Requested_Hours.flow-meta.xml
force-app/main/default/flows/Recovery_rate_less_than_70_Notify_PM.flow-meta.xml
force-app/main/default/layouts/pse__Practice__c-FFX PSA Practice Layout.layout-meta.xml

[DevOps Center] Merge WI-000457 to Integration

---

force-app/main/default/flexipages/Opportunity_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000458 to Integration

---

force-app/main/default/permissionsetgroups/cer_Finance_Custom_Permission_Set.permissionsetgroup-meta.xml

[DevOps Center] Merge WI-000459 to Integration

---

force-app/main/default/profiles/Cooper Parry Standard.profile-meta.xml

[DevOps Center] Merge WI-000460 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/Corporate_Opp_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml
force-app/main/default/layouts/PersonAccount-Person Account Layout.layout-meta.xml
force-app/main/default/objects/Account/fields/Connector_Type__c.field-meta.xml
force-app/main/default/objects/Account/fields/Date_Discovery_Session_Took_Place__c.field-meta.xml
force-app/main/default/objects/Account/fields/Discovery_Meeting_Booked__c.field-meta.xml
force-app/main/default/objects/Account/fields/Discovery_Meeting_Required__c.field-meta.xml
force-app/main/default/objects/Account/fields/Discovery_Output_Date_Sent_to_Client__c.field-meta.xml
force-app/main/default/objects/Account/fields/Fee_Insurance_Taken__c.field-meta.xml
force-app/main/default/objects/Account/fields/Tax_Grading__c.field-meta.xml
force-app/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml
force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
force-app/main/default/quickActions/Account.Onboarding.quickAction-meta.xml

[DevOps Center] Merge WI-000463 to Integration

---

force-app/main/default/flexipages/Corporate_Opp_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/Opportunity_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000464 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000466 to Integration

---

force-app/main/default/approvalProcesses/Opportunity.Law_Estimate_Approval.approvalProcess-meta.xml
force-app/main/default/approvalProcesses/Opportunity.Opportunity_Audit_Client_Approval.approvalProcess-meta.xml

[DevOps Center] Merge WI-000467 to Integration

---

force-app/main/default/flexipages/Corporate_Opp_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/Opportunity_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000469 to Integration

---

force-app/main/default/flows/Account_Risk_Team_Validation.flow-meta.xml
force-app/main/default/objects/Service_Line__c/fields/Opportunity__c.field-meta.xml
force-app/main/default/profiles/Cooper Parry Standard Platform.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard.profile-meta.xml

[DevOps Center] Merge WI-000468 to Integration

---

force-app/main/default/flexipages/Opportunity_Record_Page_Three_Column.flexipage-meta.xml
force-app/main/default/flows/Recovery_rate_less_than_70_Notify_PM.flow-meta.xml
force-app/main/default/layouts/Opportunity-pse__Opportunity Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-FFX PSA Project Detail Layout.layout-meta.xml
force-app/main/default/objects/ffscpq__Estimate__c/webLinks/New_Estimate_depricated.webLink-meta.xml
force-app/main/default/pages/newEstimateErrorPage.page
force-app/main/default/pages/newEstimateErrorPage.page-meta.xml

[DevOps Center] Merge WI-000470 to Integration

---

force-app/main/default/flows/CT_Update_Expense_for_Mileage_Receipt.flow-meta.xml
force-app/main/default/objects/pse__Expense__c/validationRules/Mileage_and_No_Car_Type_Chosen.validationRule-meta.xml

[DevOps Center] Merge WI-000471 to Integration

---

force-app/main/default/flows/Source_Screen_Flow.flow-meta.xml
force-app/main/default/objects/Account/validationRules/V6_RegisteredNumberRequired.validationRule-meta.xml
force-app/main/default/objects/Lead/fields/PE_Backed_Account__c.field-meta.xml
force-app/main/default/objects/Lead/validationRules/V3_RegisteredNumberRequired.validationRule-meta.xml

[DevOps Center] Merge WI-000474 to Integration

---

force-app/main/default/flows/Origination_Meeting_Screen_Flow.flow-meta.xml

[DevOps Center] Merge WI-000476 to Integration

---

force-app/main/default/globalValueSets/CP_Deals.globalValueSet-meta.xml
force-app/main/default/objects/Account/fields/CP_Deals_Subsector__c.field-meta.xml

[DevOps Center] Merge WI-000481 to Integration

---

force-app/main/default/objects/Lead/validationRules/V3_RegisteredNumberRequired.validationRule-meta.xml

[DevOps Center] Merge WI-000482 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
force-app/main/default/objects/Account/fields/CT_Account_access__c.field-meta.xml
force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml

[DevOps Center] Merge WI-000479 to Integration

---

force-app/main/default/globalValueSets/CP_Deals.globalValueSet-meta.xml
force-app/main/default/globalValueSets/Type_of_Business.globalValueSet-meta.xml
force-app/main/default/objects/Account/fields/CP_Deals_Subsector__c.field-meta.xml
force-app/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml
force-app/main/default/objects/Account/recordTypes/cer_Customer.recordType-meta.xml
force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml

[DevOps Center] Merge WI-000475 to Integration

---

force-app/main/default/applications/CP_PSA.app-meta.xml
force-app/main/default/applications/CP_PSAAdmin.app-meta.xml
force-app/main/default/applications/CP_PSA_Finance.app-meta.xml
force-app/main/default/applications/CP_Services_Forecasting.app-meta.xml
force-app/main/default/flexipages/Account_Record_Page_Three_Column.flexipage-meta.xml

[DevOps Center] Merge WI-000486 to Integration

---

force-app/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml
force-app/main/default/objects/Account/recordTypes/cer_Customer.recordType-meta.xml
force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml

[DevOps Center] Merge WI-000490 to Integration

---

force-app/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml
force-app/main/default/objects/Opportunity/fields/Confidential_Opportunity__c.field-meta.xml

[DevOps Center] Merge WI-000492 to Integration

---

force-app/main/default/flows/FFX_PSA_Project_Reactivation_from_Closure.flow-meta.xml
force-app/main/default/flows/Recovery_rate_less_than_70_Notify_PM.flow-meta.xml
force-app/main/default/objects/Account/validationRules/Cooper_Parry_Account_must_be_Public.validationRule-meta.xml

[DevOps Center] Merge WI-000493 to Integration

---

force-app/main/default/flows/Source_Screen_Flow.flow-meta.xml

[DevOps Center] Merge WI-000491 to Integration

---

force-app/main/default/flexipages/Beauhurst_App.flexipage-meta.xml
force-app/main/default/flows/Account_Onboarding_is_complete.flow-meta.xml

[DevOps Center] Merge WI-000494 to Integration

---

force-app/main/default/globalValueSets/CP_Deals_Subsector.globalValueSet-meta.xml

[DevOps Center] Merge WI-000496 to Integration

---

force-app/main/default/flexipages/Beauhurst_APP.flexipage-meta.xml
force-app/main/default/tabs/Beauhurst_App.tab-meta.xml

[DevOps Center] Merge WI-000497 to Integration

---

force-app/main/default/objects/Account/fields/Date_Became_Client__c.field-meta.xml

[DevOps Center] Merge WI-000499 to Integration

---

force-app/main/default/objects/Account/fields/Date_became_Client__c.field-meta.xml

[DevOps Center] Merge WI-000500 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml
force-app/main/default/flows/Account_Onboarding_is_complete.flow-meta.xml

[DevOps Center] Merge WI-000501 to Integration

---

force-app/main/default/email/FFX_PSA_Email_Templates/FFX_Skill_Cert_Rating_Approval_Request_Notification.email
force-app/main/default/email/FFX_PSA_Email_Templates/FFX_Skill_Cert_Rating_Approval_Request_Notification.email-meta.xml
force-app/main/default/flexipages/Contact_Record_Page_Three_Column.flexipage-meta.xml
force-app/main/default/layouts/pse__Skill_Certification_Rating__c-FFX_Skill%2FCertification_Rating_Layout.layout-meta.xml
force-app/main/default/layouts/pse__Skill_Certification_Rating__c-pse__Skill %2F Certification Rating Layout.layout-meta.xml
force-app/main/default/objects/pse__Skill_Certification_Rating__c/fields/Rating_Change__c.field-meta.xml
force-app/main/default/objects/pse__Skill_Certification_Rating__c/fields/Rating_before_approval_reques__c.field-meta.xml
force-app/main/default/objects/pse__Skill_Certification_Rating__c/fields/pse__Approval_Status__c.field-meta.xml
force-app/main/default/objects/pse__Skill_Certification_Rating__c/fields/pse__Rating__c.field-meta.xml
force-app/main/default/objects/pse__Time_Period__c/fields/Include_for_Revenue_Recognition__c.field-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_PSA_Custom_Fields_Permission_Set.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_PSA_Permission_Set.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_PSA_Permission_Set_for_Project_Managers.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_User_Fields.permissionset-meta.xml

[DevOps Center] Merge WI-000498 to Integration

---

force-app/main/default/flows/Account_Onboarding_is_complete.flow-meta.xml
force-app/main/default/objects/Account/fields/Date_became_Client__c.field-meta.xml

[DevOps Center] Merge WI-000502 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml
force-app/main/default/flows/Account_Onboarding_is_complete.flow-meta.xml
force-app/main/default/objects/Account/fields/Date_became_client__c.field-meta.xml

[DevOps Center] Merge WI-000503 to Integration

---

force-app/main/default/flows/CT_Release_Billing_Event.flow-meta.xml

[DevOps Center] Merge WI-000506 to Integration

---

force-app/main/default/flows/CT_Roll_Project_Forward.flow-meta.xml
force-app/main/default/flows/FFX_PSA_Project.flow-meta.xml
force-app/main/default/flows/Set_Ownercompany_on_Billing_Event.flow-meta.xml

[DevOps Center] Merge WI-000512 to Integration

---

force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000508 to Integration

---

force-app/main/default/flows/CT_Release_Billing_Event.flow-meta.xml
force-app/main/default/objects/pse__Proj__c/fields/CT_Recovery_Rate__c.field-meta.xml

[DevOps Center] Merge WI-000518 to Integration

---

force-app/main/default/flows/FFX_PSA_Project.flow-meta.xml
force-app/main/default/flows/Recovery_rate_less_than_70_Notify_PM.flow-meta.xml
force-app/main/default/layouts/pse__Proj__c-FFX PSA Project Detail Layout.layout-meta.xml
force-app/main/default/objects/ffscpq__Estimate_Line_Set__c/fields/CT_MS_Bill_Amount__c.field-meta.xml
force-app/main/default/objects/pse__Timecard_Header__c/validationRules/No_Assignment_and_No_Milestone.validationRule-meta.xml

[DevOps Center] Merge WI-000519 to Integration

---

force-app/main/default/flexipages/Lead_Record_Page.flexipage-meta.xml
force-app/main/default/layouts/Lead-Lead Layout.layout-meta.xml
force-app/main/default/objects/Lead/fields/Disqualification_Explanation__c.field-meta.xml
force-app/main/default/objects/Lead/validationRules/V4_DisqualifiedExplanation.validationRule-meta.xml
force-app/main/default/pathAssistants/Default.pathAssistant-meta.xml

[DevOps Center] Merge WI-000516 to Integration

---

force-app/main/default/roles/Audit.role-meta.xml
force-app/main/default/roles/BD.role-meta.xml
force-app/main/default/roles/BSO.role-meta.xml
force-app/main/default/roles/Deals.role-meta.xml
force-app/main/default/roles/Law.role-meta.xml
force-app/main/default/roles/Management.role-meta.xml
force-app/main/default/roles/Marketing.role-meta.xml
force-app/main/default/roles/NFP.role-meta.xml
force-app/main/default/roles/Operations.role-meta.xml
force-app/main/default/roles/Origination.role-meta.xml
force-app/main/default/roles/Pensions.role-meta.xml
force-app/main/default/roles/R_C.role-meta.xml
force-app/main/default/roles/Resourcing.role-meta.xml
force-app/main/default/roles/TS.role-meta.xml
force-app/main/default/roles/Tax.role-meta.xml

[DevOps Center] Merge WI-000520 to Integration

---

force-app/main/default/customindex/Account.Beauhurst_ID__c.indx-meta.xml
force-app/main/default/customindex/Lead.Beauhurst_ID__c.indx-meta.xml
force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
force-app/main/default/objects/Account/fields/Beauhurst_ID__c.field-meta.xml
force-app/main/default/objects/Lead/fields/Beauhurst_ID__c.field-meta.xml

[DevOps Center] Merge WI-000521 to Integration

---

force-app/main/default/profiles/Cooper Parry Standard Platform.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard.profile-meta.xml
force-app/main/default/tabs/Beauhurst_App.tab-meta.xml

[DevOps Center] Merge WI-000528 to Integration

---

force-app/main/default/flexipages/Beauhurst_App_UtilityBar.flexipage-meta.xml
force-app/main/default/objects/Cash_Entry__e/Cash_Entry__e.object-meta.xml

[DevOps Center] Merge WI-000529 to Integration

---

force-app/main/default/objects/Cash_Entry__e/fields/Currency__c.field-meta.xml
force-app/main/default/objects/Cash_Entry__e/fields/Date__c.field-meta.xml
force-app/main/default/objects/Cash_Entry__e/fields/Dual_Rate__c.field-meta.xml
force-app/main/default/objects/Cash_Entry__e/fields/Name__c.field-meta.xml
force-app/main/default/objects/Cash_Entry__e/fields/Net_Value__c.field-meta.xml
force-app/main/default/objects/Cash_Entry__e/fields/Owner_Company__c.field-meta.xml
force-app/main/default/objects/Cash_Entry__e/fields/Reference__c.field-meta.xml
force-app/main/default/objects/Cash_Entry__e/fields/Total_Cash_Entry_Value__c.field-meta.xml

[DevOps Center] Merge WI-000530 to Integration

---

force-app/main/default/objects/Invoice__e/Invoice__e.object-meta.xml
force-app/main/default/objects/Invoice__e/fields/Account_Total__c.field-meta.xml
force-app/main/default/objects/Invoice__e/fields/Currency__c.field-meta.xml
force-app/main/default/objects/Invoice__e/fields/Document_Total__c.field-meta.xml
force-app/main/default/objects/Invoice__e/fields/Dual_Rate__c.field-meta.xml
force-app/main/default/objects/Invoice__e/fields/Id__c.field-meta.xml
force-app/main/default/objects/Invoice__e/fields/Invoice_Date__c.field-meta.xml
force-app/main/default/objects/Invoice__e/fields/Name__c.field-meta.xml
force-app/main/default/objects/Invoice__e/fields/Net_Total__c.field-meta.xml
force-app/main/default/objects/Invoice__e/fields/Owner_Company__c.field-meta.xml
force-app/main/default/objects/Project__e/Project__e.object-meta.xml
force-app/main/default/objects/Project__e/fields/End_Date__c.field-meta.xml
force-app/main/default/objects/Project__e/fields/Project_Id__c.field-meta.xml
force-app/main/default/objects/Project__e/fields/Project_Name_Chain__c.field-meta.xml
force-app/main/default/objects/Project__e/fields/Project_Status__c.field-meta.xml
force-app/main/default/objects/Project__e/fields/Start_Date__c.field-meta.xml

[DevOps Center] Merge WI-000531 to Integration

---

force-app/main/default/objects/c2g__codaTransaction__c/c2g__codaTransaction__c.object-meta.xml
force-app/main/default/objects/c2g__codaTransaction__c/fields/Owner_Company__c.field-meta.xml

[DevOps Center] Merge WI-000537 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/Corporate_Opp_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/Estimate_Record_Page12.flexipage-meta.xml
force-app/main/default/flexipages/Lead_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/Service_Line_Record_Page.flexipage-meta.xml
force-app/main/default/flows/Origination_Meeting_Screen_Flow.flow-meta.xml
force-app/main/default/layouts/Service_Line__c-Service Line Layout.layout-meta.xml
force-app/main/default/objects/Lead/validationRules/V3_RegisteredNumberRequired.validationRule-meta.xml
force-app/main/default/objects/Service_Line__c/fields/Lifecycle_Coordinator__c.field-meta.xml
force-app/main/default/objects/Service_Line__c/fields/Service_Line_Manager__c.field-meta.xml
force-app/main/default/objects/Service_Line__c/fields/Service_Line_Partner__c.field-meta.xml
force-app/main/default/objects/Service_Line__c/fields/Status_Reason__c.field-meta.xml

[DevOps Center] Merge WI-000532 to Integration

---

force-app/main/default/flows/Opportunity_Create_Onboarding_Case_when_Closed_Won.flow-meta.xml

[DevOps Center] Merge WI-000534 to Integration

---

force-app/main/default/flexipages/Opportunity_Record_Page_Three_Column.flexipage-meta.xml

[DevOps Center] Merge WI-000522 to Integration

---

force-app/main/default/flows/CT_Release_Billing_Event.flow-meta.xml
force-app/main/default/layouts/pse__Proj__c-CT_PSA_Delivery_Project_Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-FFX PSA PSR Project Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-FFX PSA Project Detail Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-PSA Project Detail Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-pse__Project Detail Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-pse__Project Layout.layout-meta.xml
force-app/main/default/objects/pse__Proj__c/fieldSets/FFXCreateProjFromOppAndTempColumnsCustom.fieldSet-meta.xml
force-app/main/default/objects/pse__Proj__c/fields/CT_Actual_Recovery_Rate__c.field-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_PSA_Permission_Set.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_PSA_Permission_Set_for_Project_Managers.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_User_Fields.permissionset-meta.xml

[DevOps Center] Merge WI-000536 to Integration

---

force-app/main/default/flexipages/Opportunity_Record_Page_Three_Column.flexipage-meta.xml

[DevOps Center] Merge WI-000539 to Integration

---

force-app/main/default/layouts/Account-fferpcore__Account Layout.layout-meta.xml

[DevOps Center] Merge WI-000541 to Integration

---

force-app/main/default/flexipages/Corporate_Opp_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000543 to Integration

---

force-app/main/default/flexipages/Opportunity_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000544 to Integration

---

force-app/main/default/flows/Case_Individual_Client_Acceptance_Form.flow-meta.xml

[DevOps Center] Merge WI-000547 to Integration

---

force-app/main/default/flows/CT_Release_Billing_Event.flow-meta.xml

[DevOps Center] Merge WI-000552 to Integration

---

force-app/main/default/flows/CT_Set_Default_ProjectName.flow-meta.xml
force-app/main/default/flows/FFX_PSA_Project.flow-meta.xml
force-app/main/default/layouts/pse__Milestone__c-FFX PSA Milestone Layout.layout-meta.xml
force-app/main/default/layouts/pse__Milestone__c-pse__Milestone Layout.layout-meta.xml
force-app/main/default/layouts/pse__Practice__c-FFX PSA Practice Layout.layout-meta.xml
force-app/main/default/layouts/pse__Practice__c-pse__Practice Layout.layout-meta.xml
force-app/main/default/objects/pse__Milestone__c/fields/Recurring__c.field-meta.xml
force-app/main/default/objects/pse__Practice__c/fields/CT_Default_Recognition_Template__c.field-meta.xml
force-app/main/default/objects/pse__Practice__c/fields/CT_Project_or_Milestone_Recognition__c.field-meta.xml
force-app/main/default/objects/pse__Practice__c/listViews/pse__All.listView-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_PSA_Permission_Set.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_PSA_Permission_Set_for_Project_Managers.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_User_Fields.permissionset-meta.xml
force-app/main/default/permissionsets/FFX_FF_PSA_Full_User.permissionset-meta.xml
force-app/main/default/permissionsets/FFX_FF_PSA_Full_User_Modify_All.permissionset-meta.xml

[DevOps Center] Merge WI-000556 to Integration

---

force-app/main/default/layouts/pse__Billing_Event__c-FFX PSA Billing Event Layout.layout-meta.xml
force-app/main/default/layouts/pse__Billing_Event__c-ffpsai__Billing Event Layout %28ffpsai%29.layout-meta.xml
force-app/main/default/layouts/pse__Billing_Event__c-pse__Billing Event Layout.layout-meta.xml
force-app/main/default/objects/pse__Billing_Event__c/fields/CT_Notes_for_Finance__c.field-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_User_Fields.permissionset-meta.xml
force-app/main/default/permissionsets/FFX_FF_PSA_Full_User.permissionset-meta.xml
force-app/main/default/permissionsets/FFX_FF_PSA_Full_User_Modify_All.permissionset-meta.xml
force-app/main/default/reportTypes/FFX_Billing_Event_Batch_with_BEs_Projects.reportType-meta.xml
force-app/main/default/reportTypes/FFX_Billing_Event_Batch_with_Events_Line_Projects.reportType-meta.xml

[DevOps Center] Merge WI-000557 to Integration

---

force-app/main/default/lwc/companyHouseButton/companyHouseButton.css
force-app/main/default/lwc/companyHouseButton/companyHouseButton.html
force-app/main/default/lwc/smartSearchComp/smartSearchComp.css
force-app/main/default/lwc/smartSearchComp/smartSearchComp.html

[DevOps Center] Merge WI-000558 to Integration

---

force-app/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml
force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
force-app/main/default/standardValueSets/AccountType.standardValueSet-meta.xml

[DevOps Center] Merge WI-000562 to Integration

---

force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000563 to Integration

---

force-app/main/default/flows/Case_Risk_Team_Validation.flow-meta.xml
force-app/main/default/objects/Case/validationRules/V1_OnboardingCaseClosed.validationRule-meta.xml

[DevOps Center] Merge WI-000567 to Integration

---

force-app/main/default/approvalProcesses/Case.CAF_Form_Approval.approvalProcess-meta.xml
force-app/main/default/flexipages/Case_Record_Page.flexipage-meta.xml
force-app/main/default/flows/Case_Screenflow_Send_to_Risk.flow-meta.xml
force-app/main/default/quickActions/Case.Send_to_Risk.quickAction-meta.xml
force-app/main/default/workflows/Case.workflow-meta.xml

[DevOps Center] Merge WI-000575 to Integration

---

force-app/main/default/pathAssistants/Case_Onboarding_Path.pathAssistant-meta.xml

[DevOps Center] Merge WI-000576 to Integration

---

force-app/main/default/flexipages/Case_Record_Page.flexipage-meta.xml
force-app/main/default/flows/Case_Naming_Convention.flow-meta.xml

[DevOps Center] Merge WI-000578 to Integration

---

force-app/main/default/flows/Individual_Ongoing_Monitoring.flow-meta.xml

[DevOps Center] Merge WI-000581 to Integration

---

force-app/main/default/flows/Case_CF_CAF.flow-meta.xml
force-app/main/default/flows/Case_Individual_Client_Acceptance_Form.flow-meta.xml

[DevOps Center] Merge WI-000583 to Integration

---

force-app/main/default/layouts/pse__Billing_Event__c-FFX PSA Billing Event Layout.layout-meta.xml

[DevOps Center] Merge WI-000582 to Integration

---

force-app/main/default/flexipages/ProjectLightningPage1.flexipage-meta.xml
force-app/main/default/flexipages/time_and_expense_workspace2.flexipage-meta.xml

[DevOps Center] Merge WI-000580 to Integration

---

force-app/main/default/layouts/pse__Milestone__c-FFX PSA Milestone Layout.layout-meta.xml
force-app/main/default/layouts/pse__Milestone__c-pse__Milestone Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-CT_PSA_Delivery_Project_Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-FFX PSA PSR Project Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-PSA Project Detail Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-pse__Project Detail Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-pse__Project Layout.layout-meta.xml
force-app/main/default/objects/pse__Milestone__c/fields/CP_Complete__c.field-meta.xml
force-app/main/default/objects/pse__Milestone__c/fields/CP_Total_Costs__c.field-meta.xml
force-app/main/default/objects/pse__Proj__c/fields/CP_Complete__c.field-meta.xml
force-app/main/default/objects/pse__Proj__c/fields/CP_Total_Costs__c.field-meta.xml
force-app/main/default/objects/pse__Proj__c/fields/CT_Patent_Box_Complete__c.field-meta.xml
force-app/main/default/objects/pse__Proj__c/fields/CT_Patent_Box_Stage__c.field-meta.xml
force-app/main/default/objects/pse__Proj__c/validationRules/Not_RD_Project.validationRule-meta.xml
force-app/main/default/permissionsets/CP_Rev_Rec_Fields.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_PSA_Permission_Set.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_PSA_Permission_Set_for_Project_Managers.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_User_Fields.permissionset-meta.xml
force-app/main/default/permissionsets/FFX_FF_PSA_CRM_View_Only.permissionset-meta.xml
force-app/main/default/permissionsets/FFX_FF_PSA_Full_User.permissionset-meta.xml
force-app/main/default/permissionsets/FFX_FF_PSA_Full_User_Modify_All.permissionset-meta.xml
force-app/main/default/permissionsets/FFX_FF_PSA_Full_User_No_Cost_Fields2.permissionset-meta.xml
force-app/main/default/permissionsets/FFX_FF_PSA_Time_and_Expense_User.permissionset-meta.xml

[DevOps Center] Merge WI-000587 to Integration

---

force-app/main/default/permissionsetgroups/Asperato_User.permissionsetgroup-meta.xml
force-app/main/default/permissionsetgroups/CP_Testing_Permissionset_Group.permissionsetgroup-meta.xml
force-app/main/default/permissionsetgroups/Cooper_Parry_PSA_Accounting.permissionsetgroup-meta.xml
force-app/main/default/permissionsetgroups/Cooper_Parry_PSG_PMs_Resourcing.permissionsetgroup-meta.xml
force-app/main/default/permissionsetgroups/Cooper_Parry_TE_Resources_PSG.permissionsetgroup-meta.xml
force-app/main/default/permissionsetgroups/cer_Certinia_Accounting_Reporting.permissionsetgroup-meta.xml
force-app/main/default/permissionsetgroups/cer_Certinia_Read_Only_Accounting.permissionsetgroup-meta.xml
force-app/main/default/permissionsetgroups/cer_Finance_Custom_Permission_Set.permissionsetgroup-meta.xml

[DevOps Center] Merge WI-000588 to Integration

---

force-app/main/default/classes/QueueHttpMock.cls
force-app/main/default/classes/QueueHttpMock.cls-meta.xml

[DevOps Center] Merge WI-000593 to Integration

---

force-app/main/default/flows/Case_Send_to_Compliance_Screen_Flow.flow-meta.xml

[DevOps Center] Merge WI-000551 to Integration

---

force-app/main/default/objects/Case/validationRules/V3_FormApproval.validationRule-meta.xml

[DevOps Center] Merge WI-000597 to Integration

---

force-app/main/default/objects/Case/validationRules/V3_FormApproval.validationRule-meta.xml

[DevOps Center] Merge WI-000599 to Integration

---

force-app/main/default/classes/SharepointCompCont.cls
force-app/main/default/classes/SharepointUploadFileInvocable.cls
force-app/main/default/classes/SharepointUploadFileInvocable.cls-meta.xml
force-app/main/default/flows/Case_BTNC_Continuation_Form.flow-meta.xml
force-app/main/default/flows/Case_Client_Acceptance_Form.flow-meta.xml
force-app/main/default/lwc/sharepointComp/sharepointComp.html

[DevOps Center] Merge WI-000603 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/Case_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/Opportunity_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000602 to Integration

---

force-app/main/default/flexipages/Corporate_Opp_Record_Page.flexipage-meta.xml
force-app/main/default/flows/Opportunity_Create_Onboarding_Case_when_Closed_Won.flow-meta.xml
force-app/main/default/flows/Opportunity_Create_Service_Line_when_Closed_Won.flow-meta.xml
force-app/main/default/flows/Source_Screen_Flow.flow-meta.xml
force-app/main/default/layouts/Opportunity-Main Opportunity Layout.layout-meta.xml

[DevOps Center] Merge WI-000605 to Integration

---

force-app/main/default/flows/Case_Update_Account_when_Case_is_Closed.flow-meta.xml
force-app/main/default/objects/Account/fields/Is_Onboarded__c.field-meta.xml

[DevOps Center] Merge WI-000606 to Integration

---

force-app/main/default/flows/FFX_PSA_Project.flow-meta.xml
force-app/main/default/objects/pse__Milestone__c/fields/CT_Actual_Recovery_Rate__c.field-meta.xml
force-app/main/default/objects/pse__Proj__c/fields/CP_Total_Costs__c.field-meta.xml
force-app/main/default/objects/pse__Proj__c/fields/CT_Actual_Recovery_Rate__c.field-meta.xml

[DevOps Center] Merge WI-000607 to Integration

---

force-app/main/default/objects/Account/fields/CP_Deals_Subsector__c.field-meta.xml
force-app/main/default/objects/Journal_Line_Item__e/Journal_Line_Item__e.object-meta.xml
force-app/main/default/objects/Journal_Line_Item__e/fields/Credits__c.field-meta.xml
force-app/main/default/objects/Journal_Line_Item__e/fields/Debits__c.field-meta.xml
force-app/main/default/objects/Journal_Line_Item__e/fields/Dual_Rate__c.field-meta.xml
force-app/main/default/objects/Journal_Line_Item__e/fields/Id__c.field-meta.xml
force-app/main/default/objects/Journal_Line_Item__e/fields/Journal_Currency__c.field-meta.xml
force-app/main/default/objects/Journal_Line_Item__e/fields/Journal_Date__c.field-meta.xml
force-app/main/default/objects/Journal_Line_Item__e/fields/Name__c.field-meta.xml
force-app/main/default/objects/Journal_Line_Item__e/fields/Owner_Company__c.field-meta.xml
force-app/main/default/objects/Journal_Line_Item__e/fields/Value__c.field-meta.xml

[DevOps Center] Merge WI-000609 to Integration

---

force-app/main/default/classes/GetBeauhurstCompanies.cls
force-app/main/default/objects/Account/fields/CP_Deals_Subsector__c.field-meta.xml
force-app/main/default/objects/Transaction__e/Transaction__e.object-meta.xml
force-app/main/default/objects/Transaction__e/fields/ApexJobId__c.field-meta.xml
force-app/main/default/objects/Transaction__e/fields/AvalaraIntegrationStatus__c.field-meta.xml
force-app/main/default/objects/Transaction__e/fields/AvalaraVATReportingStatus__c.field-meta.xml
force-app/main/default/objects/Transaction__e/fields/DocumentDescription__c.field-meta.xml
force-app/main/default/objects/Transaction__e/fields/DocumentNumber__c.field-meta.xml
force-app/main/default/objects/Transaction__e/fields/DocumentReference2__c.field-meta.xml
force-app/main/default/objects/Transaction__e/fields/DocumentReference__c.field-meta.xml
force-app/main/default/objects/Transaction__e/fields/ExternalId__c.field-meta.xml
force-app/main/default/objects/Transaction__e/fields/MatchType__c.field-meta.xml
force-app/main/default/objects/Transaction__e/fields/Owner_Company__c.field-meta.xml
force-app/main/default/objects/Transaction__e/fields/ReverseReason__c.field-meta.xml
force-app/main/default/objects/Transaction__e/fields/SequentialTransactionNumber__c.field-meta.xml
force-app/main/default/objects/Transaction__e/fields/TransactionDate__c.field-meta.xml
force-app/main/default/objects/Transaction__e/fields/TransactionType__c.field-meta.xml
force-app/main/default/objects/Transaction__e/fields/UnitOfWork__c.field-meta.xml
force-app/main/default/objects/Transaction__e/fields/VendorDocumentNumber__c.field-meta.xml

[DevOps Center] Merge WI-000613 to Integration

---

force-app/main/default/globalValueSets/CP_Deals_Subsector.globalValueSet-meta.xml
force-app/main/default/objects/Client_Acceptance_Form__c/fields/mlrapick15__c.field-meta.xml

[DevOps Center] Merge WI-000615 to Integration

---

force-app/main/default/duplicateRules/Service_Line__c.Service_Line_Duplicate_Rules.duplicateRule-meta.xml
force-app/main/default/matchingRules/Service_Line__c.matchingRule-meta.xml

[DevOps Center] Merge WI-000620 to Integration

---

force-app/main/default/flexipages/Estimate_Record_Page12.flexipage-meta.xml
force-app/main/default/layouts/ffscpq__Estimate__c-ffscpq__Estimate Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-FFX PSA Project Detail Layout.layout-meta.xml

[DevOps Center] Merge WI-000614 to Integration

---

force-app/main/default/flexipages/Resource_Request_Lightning_Page1.flexipage-meta.xml
force-app/main/default/layouts/pse__Proj__c-CT_PSA_Delivery_Project_Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-FFX PSA PSR Project Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-FFX PSA Project Detail Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-PSA Project Detail Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-pse__Project Detail Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-pse__Project Layout.layout-meta.xml
force-app/main/default/layouts/pse__Resource_Request__c-FFX PSA Resource Request Layout.layout-meta.xml
force-app/main/default/layouts/pse__Resource_Request__c-pse__Resource Request Detail Layout.layout-meta.xml
force-app/main/default/layouts/pse__Resource_Request__c-pse__Resource Request Layout.layout-meta.xml
force-app/main/default/objects/pse__Proj__c/fields/Unapproved_only_for_data_migration__c.field-meta.xml
force-app/main/default/objects/pse__Resource_Request__c/fields/Unapproved_only_for_data_migration__c.field-meta.xml
force-app/main/default/permissionsets/Certinia_Cooper_Parry_Custom_PS.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_PSA_Permission_Set.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_PSA_Permission_Set_for_Project_Managers.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_User_Fields.permissionset-meta.xml
force-app/main/default/permissionsets/FFX_C_PSA_RM.permissionset-meta.xml
force-app/main/default/permissionsets/FFX_FF_PSA_CRM_View_Only.permissionset-meta.xml
force-app/main/default/permissionsets/FFX_FF_PSA_Full_User.permissionset-meta.xml
force-app/main/default/permissionsets/FFX_FF_PSA_Full_User_Modify_All.permissionset-meta.xml
force-app/main/default/permissionsets/FFX_FF_PSA_Full_User_No_Cost_Fields2.permissionset-meta.xml
force-app/main/default/permissionsets/Finance_Revenue_Recognition_Custom_Fields.permissionset-meta.xml
force-app/main/default/reportTypes/FFX_Opportunities_with_Resource_Requests.reportType-meta.xml

[DevOps Center] Merge WI-000624 to Integration

---

force-app/main/default/flows/Case_Document_Signed.flow-meta.xml

[DevOps Center] Merge WI-000626 to Integration

---

force-app/main/default/layouts/pse__Resource_Request__c-FFX PSA Resource Request Layout.layout-meta.xml

[DevOps Center] Merge WI-000628 to Integration

---

force-app/main/default/classes/SharepointUploadFileInvocable.cls
force-app/main/default/flexipages/Client_Acceptance_Form_Record_Page_Business.flexipage-meta.xml
force-app/main/default/flexipages/Client_Acceptance_Form_Record_Page_Individual.flexipage-meta.xml
force-app/main/default/flexipages/Ongoing_Monitoring_Form_Record_Page.flexipage-meta.xml
force-app/main/default/flows/Case_BTNC_Continuation_Form.flow-meta.xml
force-app/main/default/flows/Case_Client_Acceptance_Form.flow-meta.xml
force-app/main/default/flows/Individual_Ongoing_Monitoring.flow-meta.xml
force-app/main/default/layouts/Client_Acceptance_Form__c-Client Acceptance Form Layout.layout-meta.xml
force-app/main/default/layouts/Continuation_Form__c-Continuation Form Layout.layout-meta.xml

[DevOps Center] Merge WI-000630 to Integration

---

force-app/main/default/flows/CT_Project_Rev_Rec_Settings.flow-meta.xml
force-app/main/default/layouts/pse__Proj__c-FFX PSA Project Detail Layout.layout-meta.xml

[DevOps Center] Merge WI-000631 to Integration

---

force-app/main/default/profiles/Cooper Parry Standard.profile-meta.xml

[DevOps Center] Merge WI-000632 to Integration

---

force-app/main/default/profiles/Admin.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard Platform.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard.profile-meta.xml
force-app/main/default/profiles/LC.profile-meta.xml
force-app/main/default/profiles/Manager.profile-meta.xml
force-app/main/default/profiles/Partner %2F Director.profile-meta.xml
force-app/main/default/profiles/Resourcing.profile-meta.xml
force-app/main/default/profiles/Risk and Compliance.profile-meta.xml
force-app/main/default/profiles/Sales %26 Marketing.profile-meta.xml

[DevOps Center] Merge WI-000634 to Integration

---

force-app/main/default/objects/Account/recordTypes/cer_Customer.recordType-meta.xml

[DevOps Center] Merge WI-000635 to Integration

---

force-app/main/default/layouts/Account-CP Account Layout.layout-meta.xml
force-app/main/default/profiles/Admin.profile-meta.xml

[DevOps Center] Merge WI-000636 to Integration

---

force-app/main/default/permissionsetgroups/Cooper_Parry_Finance_part2.permissionsetgroup-meta.xml
force-app/main/default/permissionsetgroups/Cooper_Parry_Managers_Part_2.permissionsetgroup-meta.xml
force-app/main/default/permissionsetgroups/cer_Finance_Custom_Permission_Set.permissionsetgroup-meta.xml
force-app/main/default/permissionsets/cer_Certinia_Cooper_Parry_Account_Extension.permissionset-meta.xml

[DevOps Center] Merge WI-000640 to Integration

---

force-app/main/default/flexipages/Case_Record_Page.flexipage-meta.xml
force-app/main/default/objects/Case/recordTypes/Onboarding.recordType-meta.xml

[DevOps Center] Merge WI-000641 to Integration

---

force-app/main/default/flows/CT_Project_Rev_Rec_Settings.flow-meta.xml
force-app/main/default/flows/CT_Update_Milestone_Values.flow-meta.xml

[DevOps Center] Merge WI-000642 to Integration

---

force-app/main/default/classes/BatchCreateSharepointFolderAccount.cls
force-app/main/default/classes/BatchCreateSharepointFolderCase.cls
force-app/main/default/objects/Account/fields/Sharepoint_Public_Folder_URL__c.field-meta.xml
force-app/main/default/objects/Account/fields/Sharepoint_Secure_Folder_URL__c.field-meta.xml
force-app/main/default/objects/Case/fields/Sharepoint_Public_Folder_URL__c.field-meta.xml
force-app/main/default/objects/Case/fields/Sharepoint_Secure_Folder_URL__c.field-meta.xml

[DevOps Center] Merge WI-000643 to Integration

---

force-app/main/default/flexipages/Case_Record_Page.flexipage-meta.xml
force-app/main/default/flows/Case_Auto_Submit_Risk_Approval_after_Partner_Approval.flow-meta.xml
force-app/main/default/layouts/Continuation_Form__c-Continuation Form Layout.layout-meta.xml
force-app/main/default/objects/Case/fields/Manual_Engagement_Pack_received__c.field-meta.xml
force-app/main/default/objects/Case/webLinks/Form_Approval.webLink-meta.xml
force-app/main/default/objects/Continuation_Form__c/fields/Monitoring_Type__c.field-meta.xml
force-app/main/default/quickActions/Case.Escalation.quickAction-meta.xml

[DevOps Center] Merge WI-000627 to Integration

---

force-app/main/default/objects/pse__Proj__c/validationRules/Not_RD_Project.validationRule-meta.xml

[DevOps Center] Merge WI-000646 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
force-app/main/default/layouts/Account-CP Account Layout.layout-meta.xml
force-app/main/default/objects/Account/fields/Risk_Level_to_Account__c.field-meta.xml
force-app/main/default/quickActions/Account.LC_Update.quickAction-meta.xml
force-app/main/default/workflows/Case.workflow-meta.xml

[DevOps Center] Merge WI-000647 to Integration

---

force-app/main/default/flows/Case_Auto_Submit_Risk_Approval_after_Partner_Approval.flow-meta.xml

[DevOps Center] Merge WI-000651 to Integration

---

force-app/main/default/profiles/Cooper Parry Standard.profile-meta.xml

[DevOps Center] Merge WI-000656 to Integration

---

force-app/main/default/flexipages/Service_Line_Record_Page.flexipage-meta.xml
force-app/main/default/flows/Account_Onboarding_is_complete.flow-meta.xml
force-app/main/default/flows/Case_Update_Account_when_Case_is_Closed.flow-meta.xml
force-app/main/default/flows/Case_Update_Service_Line_to_Client_when_Closed.flow-meta.xml
force-app/main/default/layouts/Service_Line__c-Service Line Layout.layout-meta.xml
force-app/main/default/objects/Service_Line__c/fields/Case__c.field-meta.xml

[DevOps Center] Merge WI-000654 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
force-app/main/default/layouts/Account-CP Account Layout.layout-meta.xml
force-app/main/default/objects/Account/fields/Overseas_Registered_Number__c.field-meta.xml
force-app/main/default/objects/Account/fields/UK_Registered_Entity__c.field-meta.xml
force-app/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml
force-app/main/default/objects/Account/validationRules/V5_Registered_Number_Required.validationRule-meta.xml
force-app/main/default/objects/Case/recordTypes/Service_Line.recordType-meta.xml
force-app/main/default/objects/Case/validationRules/V6_Audit_Category_for_Audit_Onboarding.validationRule-meta.xml
force-app/main/default/objects/Case/validationRules/V7_Client_Amendment_Requirement.validationRule-meta.xml
force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
force-app/main/default/profiles/Admin.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard Platform.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard.profile-meta.xml
force-app/main/default/profiles/LC.profile-meta.xml
force-app/main/default/profiles/Manager.profile-meta.xml
force-app/main/default/profiles/Partner %2F Director.profile-meta.xml
force-app/main/default/profiles/Resourcing.profile-meta.xml
force-app/main/default/profiles/Risk and Compliance.profile-meta.xml
force-app/main/default/profiles/Sales %26 Marketing.profile-meta.xml

[DevOps Center] Merge WI-000658 to Integration

---

force-app/main/default/objects/Account/validationRules/V5_Registered_Number_Required.validationRule-meta.xml

[DevOps Center] Merge WI-000659 to Integration

---

force-app/main/default/flexipages/Opportunity_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000660 to Integration

---

force-app/main/default/flexipages/Case_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000664 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000665 to Integration

---

force-app/main/default/flows/Account_Ongoing_Monitoring_Schedule.flow-meta.xml

[DevOps Center] Merge WI-000668 to Integration

---

force-app/main/default/duplicateRules/Service_Line__c.Service_Line_Duplicate_Rules.duplicateRule-meta.xml

[DevOps Center] Merge WI-000672 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
force-app/main/default/layouts/Account-CP Account Layout.layout-meta.xml

[DevOps Center] Merge WI-000674 to Integration

---

force-app/main/default/flexipages/Opportunity_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000676 to Integration

---

force-app/main/default/flows/Source_Screen_Flow.flow-meta.xml

[DevOps Center] Merge WI-000677 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
force-app/main/default/layouts/Account-CP Account Layout.layout-meta.xml

[DevOps Center] Merge WI-000681 to Integration

---

force-app/main/default/flows/Source_Screen_Flow.flow-meta.xml

[DevOps Center] Merge WI-000682 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
force-app/main/default/flows/Opportunity_Audit_Estimate_Validation.flow-meta.xml
force-app/main/default/flows/Opportunity_BSO_Estimates_Validation_Rule.flow-meta.xml
force-app/main/default/flows/Opportunity_TS_TT_Estimates_Validation.flow-meta.xml
force-app/main/default/flows/Origination_Meeting_Screen_Flow.flow-meta.xml
force-app/main/default/layouts/Account-CP Account Layout.layout-meta.xml
force-app/main/default/layouts/BD_Meeting__c-BD Meeting Layout.layout-meta.xml
force-app/main/default/layouts/BD_Meeting__c-Origination Meeting Layout.layout-meta.xml
force-app/main/default/objects/Account/fields/BD__c.field-meta.xml
force-app/main/default/objects/BD_Meeting__c/fields/BD__c.field-meta.xml
force-app/main/default/profiles/Admin.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard Platform.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard.profile-meta.xml
force-app/main/default/profiles/LC.profile-meta.xml
force-app/main/default/profiles/Manager.profile-meta.xml
force-app/main/default/profiles/Partner %2F Director.profile-meta.xml
force-app/main/default/profiles/Resourcing.profile-meta.xml
force-app/main/default/profiles/Risk and Compliance.profile-meta.xml
force-app/main/default/profiles/Sales %26 Marketing.profile-meta.xml

[DevOps Center] Merge WI-000686 to Integration

---

force-app/main/default/flows/Cash_Entry_Record_Triggered_Flow.flow-meta.xml
force-app/main/default/flows/Credit_Note_Record_Triggered_Flow.flow-meta.xml
force-app/main/default/flows/Journal_Record_Triggered_Flow.flow-meta.xml
force-app/main/default/flows/Sales_Invoice_Record_Triggered_Flow.flow-meta.xml

[DevOps Center] Merge WI-000691 to Integration

---

force-app/main/default/flows/Cash_Entry_Record_Triggered_Flow.flow-meta.xml
force-app/main/default/flows/Credit_Note_Record_Triggered_Flow.flow-meta.xml
force-app/main/default/flows/Journal_Record_Triggered_Flow.flow-meta.xml
force-app/main/default/flows/Sales_Invoice_Record_Triggered_Flow.flow-meta.xml
force-app/main/default/objects/Transaction__e/fields/Transaction_Date__c.field-meta.xml
force-app/main/default/objects/Transaction__e/fields/Transaction_Type__c.field-meta.xml

[DevOps Center] Merge WI-000692 to Integration

---

force-app/main/default/objects/Account/fields/Confidential_Account_Area__c.field-meta.xml
force-app/main/default/sharingRules/Account.sharingRules-meta.xml

[DevOps Center] Merge WI-000697 to Integration

---

force-app/main/default/objects/c2g__codaInvoice__c/fields/attachSalesInvoicePdf__c.field-meta.xml

[DevOps Center] Merge WI-000701 to Integration

---

force-app/main/default/flows/CT_Update_suggested_bill_rate_on_TC_split.flow-meta.xml

[DevOps Center] Merge WI-000703 to Integration

---

force-app/main/default/objects/c2g__codaInvoice__c/fields/cer_Email_Sales_Invoice_Batch__c.field-meta.xml
force-app/main/default/objects/c2g__codaInvoice__c/fields/ffaci__CongaTemplate__c.field-meta.xml

[DevOps Center] Merge WI-000704 to Integration

---

force-app/main/default/flows/CT_Milestone_Rev_Rec_Settings.flow-meta.xml
force-app/main/default/flows/Set_RevRec_settings.flow-meta.xml
force-app/main/default/flows/Update_Suggested_Bill_rate_on_TC_Split.flow-meta.xml

[DevOps Center] Merge WI-000706 to Integration

---

force-app/main/default/flows/Set_Resource_Request_Name.flow-meta.xml

[DevOps Center] Merge WI-000708 to Integration

---

force-app/main/default/profiles/Cooper Parry Standard.profile-meta.xml
force-app/main/default/settings/Security.settings-meta.xml

[DevOps Center] Merge WI-000709 to Integration

---

force-app/main/default/objects/Case/Case.object-meta.xml
force-app/main/default/objects/Case/listViews/Escalation_Team_Queue_Case.listView-meta.xml
force-app/main/default/objects/Case/listViews/Lifecycle_Managers_Case.listView-meta.xml
force-app/main/default/objects/Case/listViews/Lifecycle_Onboarding_Queue_Case.listView-meta.xml
force-app/main/default/objects/Case/listViews/Risk_Team_Queue_Case.listView-meta.xml
force-app/main/default/objects/Case/listViews/Risk_and_Compliance_Queue_Case.listView-meta.xml
force-app/main/default/objects/Case/listViews/Service_Case_Case.listView-meta.xml
force-app/main/default/objects/Case/recordTypes/Onboarding.recordType-meta.xml
force-app/main/default/objects/Case/recordTypes/Yearly_Check.recordType-meta.xml
force-app/main/default/objects/Case/validationRules/V8_Engagement_Pack_Approval.validationRule-meta.xml
force-app/main/default/objects/Case/webLinks/APXTConga4__Conga_Composer_OAuth.webLink-meta.xml
force-app/main/default/objects/Case/webLinks/APXTConga4__Conga_Mail_Merge.webLink-meta.xml
force-app/main/default/objects/Case/webLinks/GenerateaGVKE00000000014AA.webLink-meta.xml

[DevOps Center] Merge WI-000710 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/Case_Record_Page.flexipage-meta.xml
force-app/main/default/flows/Case_Set_Ongoing_Monitoring_Date.flow-meta.xml
force-app/main/default/layouts/Case-Case Layout.layout-meta.xml

[DevOps Center] Merge WI-000711 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml
force-app/main/default/layouts/Account-CP Account Layout.layout-meta.xml
force-app/main/default/objects/Account/fields/Data_Origination_Lookup__c.field-meta.xml
force-app/main/default/profiles/Admin.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard Platform.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard.profile-meta.xml
force-app/main/default/profiles/LC.profile-meta.xml
force-app/main/default/profiles/Manager.profile-meta.xml
force-app/main/default/profiles/Partner %2F Director.profile-meta.xml
force-app/main/default/profiles/Resourcing.profile-meta.xml
force-app/main/default/profiles/Risk and Compliance.profile-meta.xml
force-app/main/default/profiles/Sales %26 Marketing.profile-meta.xml

[DevOps Center] Merge WI-000712 to Integration

---

force-app/main/default/layouts/Data_Origination__c-Data Origination Layout.layout-meta.xml
force-app/main/default/objects/Data_Origination__c/Data_Origination__c.object-meta.xml
force-app/main/default/objects/Data_Origination__c/fields/External_Id__c.field-meta.xml
force-app/main/default/profiles/Admin.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard Platform.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard.profile-meta.xml
force-app/main/default/profiles/LC.profile-meta.xml
force-app/main/default/profiles/Manager.profile-meta.xml
force-app/main/default/profiles/Partner %2F Director.profile-meta.xml
force-app/main/default/profiles/Resourcing.profile-meta.xml
force-app/main/default/profiles/Risk and Compliance.profile-meta.xml
force-app/main/default/profiles/Sales %26 Marketing.profile-meta.xml

[DevOps Center] Merge WI-000713 to Integration

---

force-app/main/default/objects/Case/validationRules/Law_Initial_Review_User_Validation.validationRule-meta.xml
force-app/main/default/objects/Case/validationRules/V9_Require_a_User_to_own_the_Case_record.validationRule-meta.xml

[DevOps Center] Merge WI-000714 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/BD_Meeting_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/Contact_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml
force-app/main/default/flows/BD_Meeting_Stamp_First_Meeting_Date.flow-meta.xml
force-app/main/default/flows/Case_BTNC_Continuation_Form.flow-meta.xml
force-app/main/default/flows/Source_Screen_Flow.flow-meta.xml
force-app/main/default/layouts/BD_Meeting__c-BD Meeting Layout.layout-meta.xml
force-app/main/default/layouts/BD_Meeting__c-Origination Meeting Layout.layout-meta.xml
force-app/main/default/layouts/Data_Origination__c-Data Origination Layout.layout-meta.xml
force-app/main/default/objects/BD_Meeting__c/fields/First_Meeting_Date__c.field-meta.xml
force-app/main/default/objects/Case/validationRules/V6_YearlyCheckValidation.validationRule-meta.xml
force-app/main/default/objects/Contact/fields/Last_Advocacy_Survey_Send_Date__c.field-meta.xml
force-app/main/default/objects/Contact/fields/Last_R_D_Survey_Send_Date__c.field-meta.xml
force-app/main/default/objects/Contact/fields/Linkedin__c.field-meta.xml
force-app/main/default/objects/Data_Origination__c/fields/Data_Origination_Report__c.field-meta.xml
force-app/main/default/profiles/Admin.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard Platform.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard.profile-meta.xml
force-app/main/default/profiles/LC.profile-meta.xml
force-app/main/default/profiles/Manager.profile-meta.xml
force-app/main/default/profiles/Partner %2F Director.profile-meta.xml
force-app/main/default/profiles/Resourcing.profile-meta.xml
force-app/main/default/profiles/Risk and Compliance.profile-meta.xml
force-app/main/default/profiles/Sales %26 Marketing.profile-meta.xml
force-app/main/default/standardValueSets/SalesTeamRole.standardValueSet-meta.xml

[DevOps Center] Merge WI-000715 to Integration

---

force-app/main/default/flows/Opportunity_Create_Service_Line_when_Closed_Won.flow-meta.xml

[DevOps Center] Merge WI-000717 to Integration

---

force-app/main/default/lwc/getCompanies/getCompanies.css
force-app/main/default/lwc/getCompanies/getCompanies.html
force-app/main/default/lwc/getCompanies/getCompanies.js
force-app/main/default/lwc/getCompanies/getCompanies.js-meta.xml

[DevOps Center] Merge WI-000719 to Integration

---

force-app/main/default/groups/Transaction_Services.group-meta.xml
force-app/main/default/groups/Transaction_Tax.group-meta.xml
force-app/main/default/workflows/Case.workflow-meta.xml

[DevOps Center] Merge WI-000718 to Integration

---

force-app/main/default/profiles/Admin.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard Platform.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard.profile-meta.xml
force-app/main/default/profiles/LC.profile-meta.xml
force-app/main/default/profiles/Manager.profile-meta.xml
force-app/main/default/profiles/Partner %2F Director.profile-meta.xml
force-app/main/default/profiles/Resourcing.profile-meta.xml
force-app/main/default/profiles/Risk and Compliance.profile-meta.xml
force-app/main/default/profiles/Sales %26 Marketing.profile-meta.xml

[DevOps Center] Merge WI-000722 to Integration

---

force-app/main/default/flexipages/BD_Meeting_Record_Page.flexipage-meta.xml
force-app/main/default/flows/Origination_Meeting_Screen_Flow.flow-meta.xml
force-app/main/default/objects/BD_Meeting__c/fields/Meeting_Notes__c.field-meta.xml

[DevOps Center] Merge WI-000723 to Integration

---

force-app/main/default/flows/CT_Update_Expense_for_Mileage_Receipt.flow-meta.xml
force-app/main/default/objects/pse__Expense__c/fields/CT_Expense_VAT_Rate__c.field-meta.xml

[DevOps Center] Merge WI-000728 to Integration

---

force-app/main/default/objects/pse__Expense__c/fieldSets/CT_Expense_Info.fieldSet-meta.xml

[DevOps Center] Merge WI-000730 to Integration

---

force-app/main/default/objects/pse__Expense__c/fields/CT_Expense_VAT_Rate__c.field-meta.xml

[DevOps Center] Merge WI-000731 to Integration

---

force-app/main/default/classes/CreateLeadsFromBHBatch.cls
force-app/main/default/classes/CreateLeadsFromBHBatch.cls-meta.xml
force-app/main/default/classes/CreateLeadsFromBHBatchTest.cls
force-app/main/default/classes/CreateLeadsFromBHBatchTest.cls-meta.xml
force-app/main/default/classes/GetCompanyCollectionBatch.cls
force-app/main/default/classes/GetCompanyCollectionBatch.cls-meta.xml
force-app/main/default/classes/GetCompanyCollectionBatchTest.cls
force-app/main/default/classes/GetCompanyCollectionBatchTest.cls-meta.xml
force-app/main/default/classes/UpdateLeadsFromBHBatch.cls
force-app/main/default/classes/UpdateLeadsFromBHBatch.cls-meta.xml
force-app/main/default/classes/UpdateLeadsFromBHBatchTest.cls
force-app/main/default/classes/UpdateLeadsFromBHBatchTest.cls-meta.xml

[DevOps Center] Merge WI-000729 to Integration

---

force-app/main/default/profiles/Survey Profile.profile-meta.xml

[DevOps Center] Merge WI-000732 to Integration

---

force-app/main/default/classes/BeauhurstAPIUtility.cls
force-app/main/default/classes/CreateAccountsFromBHBatch.cls
force-app/main/default/classes/UpdateAccountsFromBHBatch.cls

[DevOps Center] Merge WI-000735 to Integration

---

force-app/main/default/globalValueSets/Assignment_Type.globalValueSet-meta.xml
force-app/main/default/globalValueSets/Lead_Area.globalValueSet-meta.xml
force-app/main/default/globalValueSets/Type_Area.globalValueSet-meta.xml
force-app/main/default/objects/Case/recordTypes/Adhoc_Check.recordType-meta.xml
force-app/main/default/objects/Case/recordTypes/Onboarding.recordType-meta.xml
force-app/main/default/objects/Case/recordTypes/Service_Line.recordType-meta.xml
force-app/main/default/objects/Case/recordTypes/Yearly_Check.recordType-meta.xml
force-app/main/default/objects/Opportunity/recordTypes/CP_Opportunity.recordType-meta.xml
force-app/main/default/objects/Opportunity/recordTypes/Corporate_Opportunity.recordType-meta.xml

[DevOps Center] Merge WI-000739 to Integration

---

force-app/main/default/classes/UploadLeadController.cls
force-app/main/default/classes/UploadLeadController.cls-meta.xml
force-app/main/default/classes/UploadLeadControllerTest.cls
force-app/main/default/classes/UploadLeadControllerTest.cls-meta.xml

[DevOps Center] Merge WI-000737 to Integration

---

force-app/main/default/lwc/uploadLeadsComp/uploadLeadsComp.html
force-app/main/default/lwc/uploadLeadsComp/uploadLeadsComp.js
force-app/main/default/lwc/uploadLeadsComp/uploadLeadsComp.js-meta.xml

[DevOps Center] Merge WI-000742 to Integration

---

force-app/main/default/flows/Project_Async_Flow.flow-meta.xml

[DevOps Center] Merge WI-000743 to Integration

---

force-app/main/default/classes/CaseTriggerHandlerTest.cls
force-app/main/default/classes/CaseTriggerHandlerTest.cls-meta.xml

[DevOps Center] Merge WI-000745 to Integration

---

force-app/main/default/lwc/smartSearchComp/smartSearchComp.js

[DevOps Center] Merge WI-000760 to Integration

---

force-app/main/default/classes/BeauhurstAPIUtility.cls
force-app/main/default/classes/CreateAccountsFromBHBatch.cls
force-app/main/default/classes/UpdateAccountsFromBHBatch.cls

[DevOps Center] Merge WI-000762 to Integration

---

force-app/main/default/flows/CT_Set_Default_Group_on_Project.flow-meta.xml
force-app/main/default/flows/CT_Set_Default_ProjectName.flow-meta.xml
force-app/main/default/flows/CT_Set_Estimate_Defaults.flow-meta.xml

[DevOps Center] Merge WI-000750 to Integration

---

force-app/main/default/flows/Cash_Entry_Record_Triggered_Flow.flow-meta.xml

[DevOps Center] Merge WI-000764 to Integration

---

force-app/main/default/classes/CompanyLeadsComponentController.cls
force-app/main/default/classes/CompanyLeadsComponentController.cls-meta.xml
force-app/main/default/classes/DeletedClassesTest.cls
force-app/main/default/classes/DeletedClassesTest.cls-meta.xml
force-app/main/default/classes/LeadActivityMatchedController.cls
force-app/main/default/classes/LeadActivityMatchedController.cls-meta.xml
force-app/main/default/classes/LeadMatchingRuleUtility.cls
force-app/main/default/classes/LeadMatchingRuleUtility.cls-meta.xml
force-app/main/default/classes/MassConvertLeadsController.cls
force-app/main/default/classes/MassConvertLeadsController.cls-meta.xml

[DevOps Center] Merge WI-000768 to Integration

---

force-app/main/default/standardValueSets/SalesTeamRole.standardValueSet-meta.xml

[DevOps Center] Merge WI-000749 to Integration

---

force-app/main/default/objects/Opportunity/fields/Assignment_Type__c.field-meta.xml
force-app/main/default/objects/Opportunity/fields/Opportunity_Type_Area__c.field-meta.xml

[DevOps Center] Merge WI-000748 to Integration

---

force-app/main/default/flexipages/Contact_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000767 to Integration

---

force-app/main/default/globalValueSets/Primary_Sector.globalValueSet-meta.xml
force-app/main/default/globalValueSets/Type_of_Business.globalValueSet-meta.xml

[DevOps Center] Merge WI-000747 to Integration

---

force-app/main/default/flows/Opportunity_Create_Onboarding_Case_when_Closed_Won.flow-meta.xml
force-app/main/default/objects/Opportunity/businessProcesses/Renewal.businessProcess-meta.xml
force-app/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml

[DevOps Center] Merge WI-000757 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml

[DevOps Center] Merge WI-000770 to Integration

---

force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000771 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000772 to Integration

---

force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000773 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000775 to Integration

---

force-app/main/default/layouts/Referral__c-Referral Layout.layout-meta.xml
force-app/main/default/objects/Referral__c/fields/Campaign__c.field-meta.xml
force-app/main/default/profiles/Admin.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard Platform.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard.profile-meta.xml
force-app/main/default/profiles/LC.profile-meta.xml
force-app/main/default/profiles/Manager.profile-meta.xml
force-app/main/default/profiles/Partner %2F Director.profile-meta.xml
force-app/main/default/profiles/Resourcing.profile-meta.xml
force-app/main/default/profiles/Risk and Compliance.profile-meta.xml
force-app/main/default/profiles/Sales %26 Marketing.profile-meta.xml
force-app/main/default/profiles/Service Agent.profile-meta.xml
force-app/main/default/profiles/Service Supervisor.profile-meta.xml

[DevOps Center] Merge WI-000765 to Integration

---

force-app/main/default/customindex/Referral__c.External_ID__c.indx-meta.xml
force-app/main/default/objects/Referral__c/fields/External_ID__c.field-meta.xml
force-app/main/default/objects/Referral__c/fields/External_Referral_Name__c.field-meta.xml
force-app/main/default/objects/Referral__c/fields/Referral_Type__c.field-meta.xml
force-app/main/default/profiles/Admin.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard Platform.profile-meta.xml
force-app/main/default/profiles/Cooper Parry Standard.profile-meta.xml
force-app/main/default/profiles/LC.profile-meta.xml
force-app/main/default/profiles/Partner %2F Director.profile-meta.xml
force-app/main/default/profiles/Resourcing.profile-meta.xml
force-app/main/default/profiles/Risk and Compliance.profile-meta.xml
force-app/main/default/profiles/Sales %26 Marketing.profile-meta.xml
force-app/main/default/profiles/Service Agent.profile-meta.xml
force-app/main/default/profiles/Service Supervisor.profile-meta.xml

[DevOps Center] Merge WI-000776 to Integration

---

force-app/main/default/classes/AccountTriggerHandler.cls
force-app/main/default/classes/AccountTriggerHandlerTest.cls

[DevOps Center] Merge WI-000781 to Integration

---

force-app/main/default/flows/Opportunity_Update_Naming_Convention.flow-meta.xml

[DevOps Center] Merge WI-000774 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml
force-app/main/default/flows/CT_Copy_Account_Access_To_Related_Projects.flow-meta.xml
force-app/main/default/flows/CT_Handle_Delete_Action.flow-meta.xml
force-app/main/default/flows/CT_Hide_Account_for_Specific_users.flow-meta.xml

[DevOps Center] Merge WI-000779 to Integration

---

force-app/main/default/flows/Source_Screen_Flow.flow-meta.xml
force-app/main/default/profiles/End User.profile-meta.xml

[DevOps Center] Merge WI-000778 to Integration

---

force-app/main/default/objects/Account/fields/Confidential_Account_Area__c.field-meta.xml
force-app/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml
force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
force-app/main/default/sharingRules/Opportunity.sharingRules-meta.xml

[DevOps Center] Merge WI-000780 to Integration

---

force-app/main/default/groups/Confidential.group-meta.xml
force-app/main/default/objects/Opportunity/fields/Confidential_Opportunity__c.field-meta.xml
force-app/main/default/objects/Opportunity/recordTypes/CP_Opportunity.recordType-meta.xml
force-app/main/default/objects/Opportunity/recordTypes/Corporate_Opportunity.recordType-meta.xml
force-app/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml

[DevOps Center] Merge WI-000784 to Integration

---

force-app/main/default/standardValueSets/SalesTeamRole.standardValueSet-meta.xml

[DevOps Center] Merge WI-000783 to Integration

---

force-app/main/default/layouts/pse__Proj__c-FFX PSA Project Detail Layout.layout-meta.xml
force-app/main/default/objects/pse__Resource_Request__c/fieldSets/pse__CreateRRFromProjFieldSet.fieldSet-meta.xml

[DevOps Center] Merge WI-000786 to Integration

---

force-app/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml

[DevOps Center] Merge WI-000787 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000788 to Integration

---

force-app/main/default/customMetadata/Uploader_Mapping.Job_Title.md-meta.xml

[DevOps Center] Merge WI-000789 to Integration

---

force-app/main/default/objects/Account/fields/CP_Deals_Subsector__c.field-meta.xml
force-app/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml

[DevOps Center] Merge WI-000793 to Integration

---

force-app/main/default/flows/CT_Update_Project_region_from_Partner_Partner_s_region.flow-meta.xml
force-app/main/default/layouts/pse__Billing_Event_Item__c-FFX PSA Billing Event Item Layout.layout-meta.xml
force-app/main/default/layouts/pse__Billing_Event_Item__c-ffpsai__Billing Event Item Layout %28ffpsai%29.layout-meta.xml
force-app/main/default/layouts/pse__Billing_Event_Item__c-pse__Billing Event Item Layout.layout-meta.xml
force-app/main/default/layouts/pse__Milestone__c-FFX PSA Milestone Layout.layout-meta.xml
force-app/main/default/objects/pse__Billing_Event_Item__c/fields/Accounting_Line_Description__c.field-meta.xml
force-app/main/default/objects/pse__Milestone__c/fields/Milestone_Description__c.field-meta.xml
force-app/main/default/objects/pse__Proj__c/validationRules/Partners_region_vs_Project_Region.validationRule-meta.xml
force-app/main/default/permissionsets/FFX_FF_PSA_CRM_View_Only.permissionset-meta.xml
force-app/main/default/permissionsets/FFX_FF_PSA_Full_User.permissionset-meta.xml
force-app/main/default/reportTypes/FFX_Billing_Event_Batch_with_Events_Line_Projects.reportType-meta.xml

[DevOps Center] Merge WI-000794 to Integration

---

force-app/main/default/classes/CSVRecordUploaderControllerTest.cls

[DevOps Center] Merge WI-000795 to Integration

---

force-app/main/default/customindex/pse__Assignment__c.External_ID__c.indx-meta.xml
force-app/main/default/layouts/pse__Assignment__c-pse__Assignment Layout.layout-meta.xml
force-app/main/default/objects/pse__Assignment__c/fields/External_ID__c.field-meta.xml

[DevOps Center] Merge WI-000797 to Integration

---

force-app/main/default/flows/Case_Update_Service_Line_to_Client_when_Closed.flow-meta.xml
force-app/main/default/flows/Service_Line_Risk_LC_Team_Flow_Validation.flow-meta.xml

[DevOps Center] Merge WI-000798 to Integration

---

force-app/main/default/flows/Sales_Invoice_Record_Triggered_Flow.flow-meta.xml

[DevOps Center] Merge WI-000805 to Integration

---

force-app/main/default/customMetadata/ffps_cperParry__CustomMapping.Estimate.md-meta.xml
force-app/main/default/customMetadata/ffps_cperParry__CustomMapping.Fee.md-meta.xml
force-app/main/default/customMetadata/ffps_cperParry__CustomMapping.Recovery_Rate.md-meta.xml
force-app/main/default/layouts/ffscpq__Estimate__c-ffscpq__Estimate Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-FFX PSA Project Detail Layout.layout-meta.xml
force-app/main/default/objects/Opportunity/fields/OriginalProject__c.field-meta.xml
force-app/main/default/objects/ffscpq__Estimate__c/fields/CT_Current_Esimate__c.field-meta.xml
force-app/main/default/objects/ffscpq__Estimate__c/fields/CT_Original_Fee_Amount__c.field-meta.xml
force-app/main/default/objects/ffscpq__Estimate__c/fields/CT_Planned_Recovery_Rate__c.field-meta.xml
force-app/main/default/objects/ffscpq__Estimate__c/fields/Original_Project__c.field-meta.xml
force-app/main/default/permissionsets/CP_Rev_Rec_Fields.permissionset-meta.xml
force-app/main/default/permissionsets/Certinia_Cooper_Parry_Custom_PS.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_PSA_Custom_Fields_Permission_Set.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_PSA_Permission_Set.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_PSA_Permission_Set_for_Project_Managers.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_User_Fields.permissionset-meta.xml

[DevOps Center] Merge WI-000807 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000810 to Integration

---

force-app/main/default/customMetadata/ffps_cperParry__CustomMapping.Fee.md-meta.xml
force-app/main/default/flows/CT_Roll_Project_Forward.flow-meta.xml
force-app/main/default/layouts/pse__Proj__c-FFX PSA Project Detail Layout.layout-meta.xml
force-app/main/default/objects/ffscpq__Estimated_Expense__c/ffscpq__Estimated_Expense__c.object-meta.xml
force-app/main/default/objects/ffscpq__Estimated_Expense__c/fields/ffscpq__Type__c.field-meta.xml

[DevOps Center] Merge WI-000813 to Integration

---

force-app/main/default/flows/Account_Account_Status_and_Type_Automation.flow-meta.xml
force-app/main/default/flows/Opportunity_Deals_Estimates_Validation_Rule.flow-meta.xml

[DevOps Center] Merge WI-000808 to Integration

---

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
force-app/main/default/objects/Account/recordTypes/cer_Customer.recordType-meta.xml

[DevOps Center] Merge WI-000809 to Integration

---

force-app/main/default/customMetadata/ffps_cperParry__CustomMapping.PY_Fee.md-meta.xml
force-app/main/default/flexipages/Estimate_Record_Page12.flexipage-meta.xml
force-app/main/default/flexipages/ProjectLightningPage1.flexipage-meta.xml
force-app/main/default/layouts/ffscpq__Estimate_Line_Set__c-ffscpq__Estimate Line Set Layout.layout-meta.xml
force-app/main/default/objects/ffscpq__Estimate_Line_Set__c/fields/CT_MS_Prior_Year_Fee__c.field-meta.xml
force-app/main/default/objects/pse__Milestone__c/listViews/pse__All.listView-meta.xml
force-app/main/default/permissionsets/Certinia_Cooper_Parry_Custom_PS.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_PSA_Permission_Set.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_PSA_Permission_Set_for_Project_Managers.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_User_Fields.permissionset-meta.xml

[DevOps Center] Merge WI-000816 to Integration

---

force-app/main/default/layouts/pse__Proj__c-CT_PSA_Delivery_Project_Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-FFX PSA PSR Project Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-FFX PSA Project Detail Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-PSA Project Detail Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-pse__Project Detail Layout.layout-meta.xml
force-app/main/default/layouts/pse__Proj__c-pse__Project Layout.layout-meta.xml
force-app/main/default/objects/pse__Proj__c/fields/Acquisition_Marker__c.field-meta.xml
force-app/main/default/permissionsets/CP_Rev_Rec_Fields.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_PSA_Custom_Fields_Permission_Set.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_PSA_Permission_Set.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_PSA_Permission_Set_for_Project_Managers.permissionset-meta.xml
force-app/main/default/permissionsets/Cooper_Parry_User_Fields.permissionset-meta.xml

[DevOps Center] Merge WI-000817 to Integration

---

force-app/main/default/layouts/pse__Proj__c-FFX PSA Project Detail Layout.layout-meta.xml

[DevOps Center] Merge WI-000818 to Integration

---

force-app/main/default/objects/pse__Proj__c/fields/CT_Patent_Box_Complete__c.field-meta.xml
force-app/main/default/objects/pse__Proj__c/fields/CT_Patent_Box_Stage__c.field-meta.xml
force-app/main/default/objects/pse__Proj__c/fields/CT_R_D_Complete__c.field-meta.xml
force-app/main/default/objects/pse__Proj__c/fields/CT_R_D_Stage__c.field-meta.xml

[DevOps Center] Merge WI-000821 to Integration
